import type { PuzzleSpec } from '../types.js';

export const sealIn: PuzzleSpec = {
  kind: 'ladder',
  slug: 'seal-in',
  title: 'Start / Stop Seal-In',
  difficulty: 'easy',
  order: 2,
  category: 'basics',
  summary: 'Latch a motor with momentary Start/Stop buttons using a seal-in contact.',
  briefing: [
    'A conveyor motor is started and stopped from two momentary push buttons. A',
    'momentary button only makes contact while it is held, so the program has to',
    'remember that the motor was started. This is the classic seal-in (hold-in)',
    'circuit, and almost every rung you write from here on is built on it.',
    '',
    '## Equipment',
    '- X0 START: momentary push button, normally open.',
    '- X1 STOP: momentary push button.',
    '- Y0 MOTOR: the contactor that runs the drive.',
    '',
    '## Sequence of operation',
    '1. Press START. The motor contactor Y0 pulls in.',
    '2. Release START. The motor keeps running: a normally-open Y0 contact in parallel',
    '   with the button holds the rung in.',
    '3. Press STOP. The rung breaks and the motor drops out.',
    '4. Release STOP. The motor stays off until START is pressed again.',
    '',
    '## Field notes',
    '- With no button touched, the motor must never start on its own.',
    '- STOP belongs in series with the whole start-and-seal group. Put it anywhere else',
    '  and the seal-in contact simply bypasses it.',
  ].join('\n'),
  hints: [
    'Put X0 (NO) and Y0 (NO) in parallel using a vertical link.',
    'Place STOP (X1) as a normally-closed contact in series before the coil.',
    'The motor coil is Y0.',
  ],
  devices: [
    { address: 'X0', label: 'Start', io: 'input', widget: 'momentary' },
    { address: 'X1', label: 'Stop', io: 'input', widget: 'momentary' },
    { address: 'Y0', label: 'Motor', io: 'output', widget: 'motor', color: '#38bdf8' },
  ],
  allowedInstructions: ['contact-no', 'contact-nc', 'coil-out'],
  maxRungs: 1,
  processId: 'passthrough',
  scenarios: [
    {
      name: 'Start latches and seals in',
      steps: [
        { label: 'Idle', holdMs: 100, expect: { Y0: false } },
        { label: 'Press Start', setInputs: { X0: true }, holdMs: 150, expect: { Y0: true } },
        { label: 'Release Start', setInputs: { X0: false }, holdMs: 200, expect: { Y0: true } },
      ],
    },
    {
      name: 'Stop drops the motor',
      steps: [
        { label: 'Press Start', setInputs: { X0: true }, holdMs: 100, expect: { Y0: true } },
        { label: 'Release Start', setInputs: { X0: false }, holdMs: 100, expect: { Y0: true } },
        { label: 'Press Stop', setInputs: { X1: true }, holdMs: 100, expect: { Y0: false } },
        { label: 'Release Stop', setInputs: { X1: false }, holdMs: 100, expect: { Y0: false } },
      ],
    },
    {
      name: 'Motor stays off on its own',
      steps: [{ label: 'No buttons', holdMs: 300, expect: { Y0: false } }],
    },
  ],
};
