import type { PuzzleSpec } from '../types.js';

export const conveyorStop: PuzzleSpec = {
  kind: 'ladder',
  slug: 'conveyor-stop',
  title: 'Index to Sensor',
  difficulty: 'easy',
  order: 8,
  category: 'stations',
  summary: 'Run a conveyor until a part reaches the sensor, then stop automatically.',
  briefing: [
    'A conveyor indexes a part into a work cell and has to park it accurately under',
    'the tooling. Commission the index stroke.',
    '',
    '## Equipment',
    '- X0 START and X1 STOP: momentary push buttons.',
    '- X2 PART SENSOR: a through-beam sensor at the end stop, driven by the machine.',
    '  You cannot press it yourself.',
    '- Y0 BELT: the conveyor drive.',
    '',
    '## Sequence of operation',
    '1. Press START. The belt Y0 runs and seals in, so the operator can let go.',
    '2. The part rides down the belt toward the work cell.',
    '3. The part reaches the sensor X2. The belt stops on its own, leaving the part',
    '   in position under the tooling.',
    '4. The belt stays stopped until the next START.',
    '',
    '## Interlocks and safety',
    '- STOP must halt the belt at any time, before or after the part arrives.',
    '- The sensor has to break the seal-in itself. A rung that only stops on the',
    '  button will run the part straight past the work cell.',
  ].join('\n'),
  hints: [
    'Start from the seal-in circuit: (X0 OR Y0) in series with normally-closed X1.',
    'Add a normally-closed X2 contact in series so the belt drops when the part arrives.',
    'The belt is Y0; the sensor is X2.',
  ],
  devices: [
    { address: 'X0', label: 'Start', io: 'input', widget: 'momentary' },
    { address: 'X1', label: 'Stop', io: 'input', widget: 'momentary' },
    { address: 'X2', label: 'Part Sensor', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: 'Belt', io: 'output', widget: 'motor', color: '#38bdf8' },
  ],
  allowedInstructions: ['contact-no', 'contact-nc', 'coil-out'],
  maxRungs: 1,
  processId: 'conveyor',
  scenarios: [
    {
      name: 'Belt runs then stops at the sensor',
      steps: [
        { label: 'Press Start: belt runs', setInputs: { X0: true }, holdMs: 500, expect: { Y0: true, X2: false } },
        { label: 'Release Start: belt seals in', setInputs: { X0: false }, holdMs: 200, expect: { Y0: true } },
        { label: 'Part reaches sensor: belt stops', holdMs: 900, expect: { Y0: false, X2: true } },
        { label: 'Belt stays stopped', holdMs: 300, expect: { Y0: false } },
      ],
    },
    {
      name: 'Stop halts the belt early',
      steps: [
        { label: 'Start the belt', setInputs: { X0: true }, holdMs: 200, expect: { Y0: true } },
        { label: 'Release Start', setInputs: { X0: false }, holdMs: 100, expect: { Y0: true } },
        { label: 'Press Stop before the part arrives', setInputs: { X1: true }, holdMs: 150, expect: { Y0: false } },
      ],
    },
  ],
};
