import type { PuzzleSpec } from '../types.js';

export const elevatorDoors: PuzzleSpec = {
  kind: 'ladder',
  slug: 'elevator-doors',
  title: 'Elevator — Doors',
  difficulty: 'hard',
  order: 13,
  category: 'elevator',
  summary: 'Add a door that opens on arrival, dwells, and auto-closes — the car cannot move until it does.',
  briefing: [
    'The same 5-floor dispatch car, now with a door. The car physically cannot move',
    "while the door isn't fully closed (X16) — this is enforced by the machine itself,",
    'not just graded, so getting the dispatch wiring from the previous puzzle wrong in a',
    'way that tries to move early will simply leave the car sitting still with the door',
    'open rather than doing something unsafe.',
    '',
    'On arriving at any floor the car is actually stopping at, open the door (Y2) and',
    'hold it open for 3 seconds (X15 confirms open), then close it automatically so the',
    'car is free to continue dispatching. Do not open the door while merely passing',
    'through a floor without stopping.',
  ].join('\n'),
  hints: [
    'Reuse the dispatch/stop logic from the 5-Floor Dispatch puzzle unchanged — the door',
    'interlock is physical, so it does not need to be wired into the Up/Down latches.',
    'Open the door on a RISING EDGE of a floor-arrival sensor, gated by the Up and Down',
    'latches both being off that same scan — that tells a genuine stop apart from a',
    "pass-through, since a pass-through leaves at least one latch still set. A level",
    "contact instead of an edge would reopen the door every scan for as long as the",
    'car sits parked, even after it has already closed once.',
    'Run an on-delay timer (K30 = 3.0 s) while the door is open (X15); when it finishes,',
    'clear the door-open latch so the door retracts.',
  ],
  devices: [
    { address: 'X0', label: 'Call Floor 1', io: 'input', widget: 'momentary' },
    { address: 'X1', label: 'Call Floor 2', io: 'input', widget: 'momentary' },
    { address: 'X2', label: 'Call Floor 3', io: 'input', widget: 'momentary' },
    { address: 'X3', label: 'Call Floor 4', io: 'input', widget: 'momentary' },
    { address: 'X4', label: 'Call Floor 5', io: 'input', widget: 'momentary' },
    { address: 'X10', label: 'At Floor 1', io: 'input', widget: 'sensor' },
    { address: 'X11', label: 'At Floor 2', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'At Floor 3', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'At Floor 4', io: 'input', widget: 'sensor' },
    { address: 'X14', label: 'At Floor 5', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Door Open', io: 'input', widget: 'sensor' },
    { address: 'X16', label: 'Door Closed', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: 'Motor Up', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: 'Motor Down', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y2', label: 'Door Open Command', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'M0', label: 'Call Lamp 1', io: 'output', widget: 'lamp' },
    { address: 'M1', label: 'Call Lamp 2', io: 'output', widget: 'lamp' },
    { address: 'M2', label: 'Call Lamp 3', io: 'output', widget: 'lamp' },
    { address: 'M3', label: 'Call Lamp 4', io: 'output', widget: 'lamp' },
    { address: 'M4', label: 'Call Lamp 5', io: 'output', widget: 'lamp' },
  ],
  registers: [
    { address: 'M5', label: 'Up latch', note: 'drives Y0; set/cleared per floor' },
    { address: 'M6', label: 'Down latch', note: 'drives Y1; set/cleared per floor' },
    { address: 'M11', label: 'Above(3)', note: 'call pending on floor 4 or 5' },
    { address: 'M12', label: 'Above(2)', note: 'call pending on floor 3, 4 or 5' },
    { address: 'M13', label: 'Above(1)', note: 'call pending on floor 2, 3, 4 or 5' },
    { address: 'M15', label: 'Below(3)', note: 'call pending on floor 1 or 2' },
    { address: 'M16', label: 'Below(4)', note: 'call pending on floor 1, 2 or 3' },
    { address: 'M17', label: 'Below(5)', note: 'call pending on floor 1, 2, 3 or 4' },
    { address: 'M20', label: 'Door open latch', note: 'drives Y2; cleared by the dwell timer' },
    { address: 'T1', label: 'Dwell timer', note: 'on-delay, preset K30 = 3.0 s' },
  ],
  allowedInstructions: ['contact-no', 'contact-nc', 'contact-rising', 'coil-out', 'coil-set', 'coil-reset', 'timer'],
  maxRungs: 28,
  processId: 'elevator5',
  scenarios: [
    {
      name: 'Door opens on arrival, dwells, then auto-closes',
      steps: [
        { label: 'Press call for floor 3', setInputs: { X2: true }, holdMs: 150, expect: { M2: true } },
        {
          label: 'Release — car climbs and arrives',
          setInputs: { X2: false },
          holdMs: 2200,
          expect: { X12: true, Y0: false },
        },
        { label: 'Door finishes opening', holdMs: 700, expect: { X15: true, X16: false } },
        { label: 'Door dwells open (well under 3 s) — still open', holdMs: 2000, expect: { X15: true, X16: false } },
        { label: 'After the dwell the door auto-closes', holdMs: 2200, expect: { X16: true, X15: false } },
      ],
    },
    {
      name: 'The car cannot move while the door is open',
      steps: [
        { label: 'Press call for floor 4', setInputs: { X3: true }, holdMs: 150, expect: { M3: true } },
        {
          label: 'Release — car climbs and arrives',
          setInputs: { X3: false },
          holdMs: 3000,
          expect: { X13: true },
        },
        { label: 'Door finishes opening', holdMs: 700, expect: { X15: true } },
        {
          label: 'While dwelling, the car has not moved off floor 4',
          holdMs: 1000,
          expect: { X13: true, X15: true },
        },
      ],
    },
    {
      name: 'A call pressed mid-dwell is serviced only once the door is confirmed closed',
      steps: [
        { label: 'Press call for floor 3', setInputs: { X2: true }, holdMs: 150, expect: { M2: true } },
        {
          label: 'Release — car climbs and arrives',
          setInputs: { X2: false },
          holdMs: 2200,
          expect: { X12: true },
        },
        { label: 'Door finishes opening', holdMs: 700, expect: { X15: true } },
        {
          label: 'Press call for floor 5 mid-dwell — car still parked at floor 3',
          setInputs: { X4: true },
          holdMs: 1000,
          expect: { X12: true, X15: true },
        },
        {
          label: 'Door closes and the queued call is finally serviced',
          setInputs: { X4: false },
          holdMs: 4200,
          expect: { X14: true, Y0: false, M4: false },
        },
      ],
    },
  ],
};
