import type { PuzzleSpec } from '../types.js';

export const cabinetDol: PuzzleSpec = {
  kind: 'cabinet',
  slug: 'cabinet-dol',
  title: 'DOL Motor Starter',
  difficulty: 'medium',
  order: 16,
  category: 'control-cabinet',
  summary: 'Wire a direct-on-line 400V starter: contactor, overload, start/stop with seal-in.',
  briefing: [
    'Commission a direct-on-line (DOL) starter for the 400 V motor M1. A DOL starter',
    'switches all three phases with one contactor and protects the motor with a',
    'thermal overload relay.',
    '',
    '## Equipment',
    '- K1 CONTACTOR: mains 1-2, 3-4, 5-6; coil A1-A2; auxiliaries 13-14 (NO) and',
    '  21-22 (NC).',
    '- F1 THERMAL OVERLOAD: mains 1-2, 3-4, 5-6; contact 95-96 opens on a trip.',
    '- S1 START (NO, 13-14) and S2 STOP (NC, 21-22).',
    '- M1 MOTOR: terminals U, V, W.',
    '',
    '## Power circuit',
    '1. Feed each phase into the contactor mains: L1 to K1.1, L2 to K1.3, L3 to K1.5.',
    '2. Carry each phase on through the overload: K1.2 to F1.1, and likewise 4 to 3',
    '   and 6 to 5.',
    '3. Land the overload outputs on the motor in phase order: F1.2 to U, F1.4 to V,',
    '   F1.6 to W. That order is what makes the motor run forward.',
    '',
    '## Control circuit',
    '1. Start at L1 and pass through the STOP contact S2 (21-22), so pressing STOP',
    '   breaks the rung.',
    '2. Continue through the START contact S1 (13-14).',
    '3. Into the contactor coil K1.A1-A2.',
    '4. Out through the overload contact F1 95-96 to N, so a trip drops the coil.',
    '5. Seal in across the START button with the contactor\'s own auxiliary K1 13-14,',
    '   so the motor keeps running once the operator lets go.',
    '',
    '## Acceptance',
    '- START runs the motor forward and seals in; STOP drops it.',
    '- Tripping the overload with the panel toggle stops the motor and blocks a',
    '  restart until it is reset.',
  ].join('\n'),
  hints: [
    'Control path: L1 → S2.21 … S2.22 → S1.13 … S1.14 → K1.A1 … K1.A2 → F1.95 … F1.96 → N.',
    'Seal-in: wire K1.13 to S1.13 and K1.14 to S1.14, so the aux contact bridges the START button once K1 pulls in.',
    'Power path per phase: L1 → K1.1, K1.2 → F1.1, F1.2 → U (and likewise 3/4 → V, 5/6 → W).',
    'Use the "Overload trip (test)" toggle on the operator panel to verify the trip behavior.',
  ],
  devices: [
    { address: 'S1', label: 'Start', io: 'input', widget: 'momentary' },
    { address: 'S2', label: 'Stop', io: 'input', widget: 'momentary' },
    { address: 'F1T', label: 'Overload trip (test)', io: 'input', widget: 'toggle' },
    { address: 'K1', label: 'Contactor', io: 'output', widget: 'lamp', color: '#f59e0b' },
    { address: 'M1', label: 'Motor', io: 'output', widget: 'motor', color: '#38bdf8' },
  ],
  cabinet: {
    // Panel: two DIN-rail rows (supply + contactor, then the overload),
    // start/stop buttons on the door strip, motor below the enclosure.
    components: [
      { id: 'PS', type: 'supply3ph', label: '400V supply', x: 250, y: 80 },
      { id: 'K1', type: 'contactor', label: 'Contactor', hmiAddress: 'K1', x: 430, y: 80 },
      { id: 'F1', type: 'overload', label: 'Overload relay', hmiAddress: 'F1T', x: 250, y: 220 },
      { id: 'S1', type: 'button-no', label: 'Start', hmiAddress: 'S1', x: 70, y: 150 },
      { id: 'S2', type: 'button-nc', label: 'Stop', hmiAddress: 'S2', x: 70, y: 250 },
      { id: 'M1', type: 'motor3', label: 'Motor', hmiAddress: 'M1', x: 430, y: 380 },
    ],
    // Diagram sheet: power circuit on the left (rails → K1 main → F1 main →
    // motor), control rung on the right, spare contacts parked at the margin.
    schematic: [
      { componentId: 'PS', part: 'phases', x: 140, y: 40 },
      { componentId: 'K1', part: 'main', x: 140, y: 140 },
      { componentId: 'F1', part: 'main', x: 140, y: 240 },
      { componentId: 'M1', part: 'motor', x: 140, y: 350 },
      { componentId: 'S2', part: 'contact', x: 420, y: 120 },
      { componentId: 'S1', part: 'contact', x: 420, y: 210 },
      { componentId: 'K1', part: 'aux13', x: 500, y: 210 },
      { componentId: 'K1', part: 'coil', x: 420, y: 310 },
      { componentId: 'F1', part: 'aux95', x: 420, y: 400 },
      { componentId: 'PS', part: 'npe', x: 420, y: 490 },
      { componentId: 'K1', part: 'aux21', x: 590, y: 120 },
      { componentId: 'F1', part: 'aux97', x: 590, y: 210 },
    ],
  },
  maxWires: 24,
  scenarios: [
    {
      name: 'Start and seal in',
      steps: [
        { label: 'At rest', holdMs: 100, expect: { K1: false, M1: false } },
        {
          label: 'Press Start',
          setInputs: { S1: true },
          holdMs: 150,
          expect: { K1: true, M1: true },
          expectMachine: { M1_direction: 'fwd' },
        },
        {
          label: 'Release Start',
          setInputs: { S1: false },
          holdMs: 200,
          expect: { K1: true, M1: true },
        },
      ],
    },
    {
      name: 'Stop drops the motor',
      steps: [
        { label: 'Press Start', setInputs: { S1: true }, holdMs: 100, expect: { M1: true } },
        { label: 'Release Start', setInputs: { S1: false }, holdMs: 100, expect: { M1: true } },
        { label: 'Press Stop', setInputs: { S2: true }, holdMs: 100, expect: { K1: false, M1: false } },
        { label: 'Release Stop', setInputs: { S2: false }, holdMs: 150, expect: { K1: false, M1: false } },
      ],
    },
    {
      name: 'Overload trip protects the motor',
      steps: [
        { label: 'Start the motor', setInputs: { S1: true }, holdMs: 100, expect: { M1: true } },
        { label: 'Release Start', setInputs: { S1: false }, holdMs: 100, expect: { M1: true } },
        {
          label: 'Overload trips',
          setInputs: { F1T: true },
          holdMs: 150,
          expect: { K1: false, M1: false },
        },
        {
          label: 'Overload resets: no self-restart',
          setInputs: { F1T: false },
          holdMs: 200,
          expect: { K1: false, M1: false },
        },
      ],
    },
    {
      name: 'Nothing runs on its own',
      steps: [
        {
          label: 'No buttons pressed',
          holdMs: 300,
          expect: { K1: false, M1: false },
          expectMachine: { shorted: false },
        },
      ],
    },
  ],
};
