import type { PuzzleSpec } from '../types.js';

export const packBasics: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pack-basics',
  title: 'Packer: Match & Push Pairs',
  difficulty: 'easy',
  order: 21,
  category: 'packaging',
  summary: 'Boxes arrive on two lanes. When a pair lines up at the stop, push it into section 2.',
  briefing: [
    'Welcome to the box packer. Boxes arrive on two lanes and ride to an end stop, but',
    'the lanes do not stay in step. This work order commissions the 2-pack pusher that',
    'shoves matched pairs off the belt into section 2.',
    '',
    '## Equipment',
    '- X14 BOX AT STOP (near) and X15 BOX AT STOP (far): one per lane, made when that',
    '  lane\'s box has reached the end stop.',
    '- Y0 2-PACK PUSHER: a pneumatic cylinder. Energize it and it extends; drop it and',
    '  a spring retracts it.',
    '- X0 2-PACK IN and X1 2-PACK OUT: the cylinder\'s end-of-stroke sensors.',
    '',
    '## Sequence of operation',
    '1. The feed belt runs continuously and the machine starts empty. Boxes travel to',
    '   the stop on their own.',
    '2. Wait until both lanes have a box at the stop.',
    '3. Extend the pusher and hold the stroke all the way out to X1. That single stroke',
    '   delivers the pair into section 2.',
    '4. Drop the output. The spring returns the plate to X0 and the lanes refill for',
    '   the next pair.',
    '',
    '## Interlocks and safety',
    '- Never push with only one box at the stop. A single box goes in askew and jams',
    '  the machine.',
    '- Both boxes leave the sensors the moment the plate starts moving, so seal the',
    '  stroke in and let OUT (X1) break the seal. A bare "both sensors made" rung lets',
    '  go mid-stroke.',
    '- While the plate is away its L-gate blocks the lanes, so arriving boxes hold',
    '  short of the stop until the pusher is home again.',
  ].join('\n'),
  hints: [
    'This is the classic seal-in with a twist: start on X14 AND X15, hold via a Y0 ' +
      'branch, and put a normally-closed X1 in series to end the stroke.',
    'One rung is enough: (X14·X15 ∥ Y0) · X1(NC) → Y0.',
    'The machine refeeds itself: after the pusher comes home, the next two boxes ' +
      'advance to the stop and the same rung fires again. Two strokes stage a 4-pack.',
  ],
  devices: [
    { address: 'X14', label: 'Box at Stop (near)', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Box at Stop (far)', io: 'input', widget: 'sensor' },
    { address: 'X0', label: '2-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X1', label: '2-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: '2-Pack Pusher', io: 'output', widget: 'motor', color: '#38bdf8' },
  ],
  allowedInstructions: ['contact-no', 'contact-nc', 'coil-out'],
  maxRungs: 2,
  processId: 'packaging',
  scenarios: [
    {
      name: 'Every matched pair gets one full stroke',
      steps: [
        {
          label: 'Machine starts empty: boxes still travelling',
          holdMs: 500,
          expect: { Y0: false, X14: false },
        },
        {
          label: 'Near box at the stop, far box still coming: no push yet',
          holdMs: 800,
          expect: { X14: true, X15: false, Y0: false },
        },
        { label: 'Pair matched: pusher strokes out', holdMs: 500, expect: { Y0: true } },
        {
          label: 'Pair delivered to section 2: pusher springs home',
          holdMs: 800,
          expect: { Y0: false },
          expectMachine: { sec2: 2, jam: false },
        },
        { label: 'Next pair lines up: second stroke', holdMs: 700, expect: { Y0: true } },
        {
          label: 'Four boxes staged in two steps',
          holdMs: 1000,
          expect: { Y0: false },
          expectMachine: { sec2: 4, jam: false },
        },
      ],
    },
    {
      name: 'No premature stroke while the lanes fill',
      steps: [
        { label: 'Belt running, nothing at the stop yet: pusher rests', holdMs: 1000, expect: { Y0: false, X14: false } },
      ],
    },
  ],
};
