import type { PuzzleSpec } from '../types.js';

export const packGroup: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pack-group',
  title: 'Packer: Stage the 4-Pack',
  difficulty: 'medium',
  order: 22,
  category: 'packaging',
  summary: 'Count two pair-strokes into section 2, then push the finished 4-pack onto the lift.',
  briefing: [
    'Section 2 holds four boxes in a file: each 2-PACK stroke (Y0) shoves a fresh',
    'pair in and steps the previous pair deeper, so TWO strokes stage a 4-pack. The',
    '4-PACK PUSHER (Y1, sensors IN X2 / OUT X3) then pushes the whole file sideways',
    'onto the lift platform. It may only do that while the lift is DOWN (X4) and',
    'section 2 is actually full.',
    '',
    'Keep the pair pusher from the last puzzle running, but two new rules now apply:',
    '',
    '  1. Y0 must not stroke while the 4-pack cylinder is away from home (X2): its',
    '     L-gate crosses the section 2 entry and the pair would jam against it. And',
    '     once two strokes are in, hold off on a third pair until the 4-pack has',
    '     cleared out.',
    '  2. Count the pair strokes on a counter (C0, preset K2). When it completes and',
    '     the lift is down, drive Y1 out; reset C0 when Y1 reaches OUT (X3) so the',
    '     4-pack pusher retracts and the count starts over for the next group.',
    '',
    'The lift itself has no controls in this puzzle; the 4-pack just waits on the',
    'platform. Get one full group staged and loaded without a jam.',
  ].join('\n'),
  hints: [
    'Extend the pair rung\'s start condition: X14 · X15 · X2 · C0(NC), still sealed',
    'with Y0 and broken by X1(NC). The C0(NC) contact is what stops a third pair.',
    'Count the strokes off the OUT sensor: X1 → C0 (K2). The counter steps on each',
    'rising edge, so one stroke = one count.',
    'Load the lift with C0 · X4 → Y1. Reset with X3 → RST C0 — dropping the counter',
    'also drops Y1, which is what lets it spring home.',
  ],
  devices: [
    { address: 'X14', label: 'Box at Stop (near)', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Box at Stop (far)', io: 'input', widget: 'sensor' },
    { address: 'X0', label: '2-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X1', label: '2-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X2', label: '4-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X3', label: '4-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'Lift Down', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: '2-Pack Pusher', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: '4-Pack Pusher', io: 'output', widget: 'motor', color: '#f59e0b' },
  ],
  registers: [{ address: 'C0', label: 'Pair-stroke counter', note: 'preset K2 — two strokes = one 4-pack' }],
  allowedInstructions: ['contact-no', 'contact-nc', 'coil-out', 'counter', 'coil-reset'],
  maxRungs: 6,
  processId: 'packaging',
  scenarios: [
    {
      name: 'Two strokes build the 4-pack, then it loads the lift',
      steps: [
        {
          label: 'First pair pushed in',
          holdMs: 1800,
          expect: { Y0: true, Y1: false },
        },
        {
          label: 'One pair staged — 4-pack pusher stays home',
          holdMs: 800,
          expect: { Y1: false },
          expectMachine: { sec2: 2, jam: false },
        },
        { label: 'Second pair in — count complete, 4-pack strokes out', holdMs: 1300, expect: { Y1: true } },
        {
          label: '4-pack delivered to the lift — pusher springs home',
          holdMs: 700,
          expect: { Y1: false },
          expectMachine: { liftLoad: 4, sec2: 0, jam: false },
        },
        {
          label: 'Next pair stages, but no second 4-pack push',
          holdMs: 1100,
          expect: { Y1: false },
          expectMachine: { sec2: 2, liftLoad: 4, jam: false },
        },
      ],
    },
    {
      name: 'Machine starts empty — everything rests',
      steps: [{ label: 'Lanes still filling, no strokes', holdMs: 900, expect: { Y0: false, Y1: false } }],
    },
  ],
};
