import type { PuzzleSpec } from '../types.js';

export const packGroup: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pack-group',
  title: 'Packer: Stage the 4-Pack',
  difficulty: 'medium',
  order: 22,
  category: 'packaging',
  summary: 'Count two pair-strokes into section 2, then push the finished 4-pack onto the lift.',
  briefing: [
    'Section 2 holds four boxes in a file. Each pair stroke shoves a fresh pair in and',
    'steps the previous pair deeper, so two strokes stage a 4-pack. This work order',
    'adds the stroke counter and the 4-pack pusher that loads the lift.',
    '',
    '## Equipment',
    '- Everything from the pair-stroke work order, unchanged.',
    '- Y1 4-PACK PUSHER, with sensors X2 4-PACK IN and X3 4-PACK OUT.',
    '- X4 LIFT DOWN: made while the lift platform is parked at the bottom.',
    '- C0: pair-stroke counter, preset K2 (see Working Registers).',
    '',
    '## Sequence of operation',
    '1. Keep the pair pusher running as commissioned, with the two new conditions on',
    '   its start listed below.',
    '2. Count each completed pair stroke on C0. Two counts means section 2 holds a',
    '   full 4-pack.',
    '3. With the count complete and the lift DOWN (X4), drive the 4-pack pusher Y1 out.',
    '   It sweeps the whole file sideways onto the lift platform.',
    '4. When Y1 reaches OUT (X3), reset C0. Dropping the count drops the pusher, which',
    '   springs home, and the tally starts over for the next group.',
    '',
    '## Interlocks and safety',
    '- Do not stroke the pair pusher while the 4-pack cylinder is away from home (X2).',
    '  Its L-gate crosses the section 2 entry and the pair jams against it.',
    '- Do not stage a third pair before the finished 4-pack has cleared out.',
    '- The lift has no controls in this work order. The 4-pack simply waits on the',
    '  platform.',
    '',
    '## Acceptance',
    '- One full group staged and loaded onto the lift without a jam.',
  ].join('\n'),
  hints: [
    'Extend the pair rung\'s start condition: X14 · X15 · X2 · C0(NC), still sealed ' +
      'with Y0 and broken by X1(NC). The C0(NC) contact is what stops a third pair.',
    'Count the strokes off the OUT sensor: X1 → C0 (K2). The counter steps on each ' +
      'rising edge, so one stroke = one count.',
    'Load the lift with C0 · X4 → Y1. Reset with X3 → RST C0. Dropping the counter ' +
      'also drops Y1, which is what lets it spring home.',
  ],
  devices: [
    { address: 'X14', label: 'Box at Stop (near)', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Box at Stop (far)', io: 'input', widget: 'sensor' },
    { address: 'X0', label: '2-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X1', label: '2-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X2', label: '4-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X3', label: '4-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'Lift Down', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: '2-Pack Pusher', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: '4-Pack Pusher', io: 'output', widget: 'motor', color: '#f59e0b' },
  ],
  registers: [{ address: 'C0', label: 'Pair-stroke counter', note: 'preset K2: two strokes = one 4-pack' }],
  allowedInstructions: ['contact-no', 'contact-nc', 'coil-out', 'counter', 'coil-reset'],
  maxRungs: 6,
  processId: 'packaging',
  scenarios: [
    {
      name: 'Two strokes build the 4-pack, then it loads the lift',
      steps: [
        {
          label: 'First pair pushed in',
          holdMs: 1800,
          expect: { Y0: true, Y1: false },
        },
        {
          label: 'One pair staged: 4-pack pusher stays home',
          holdMs: 800,
          expect: { Y1: false },
          expectMachine: { sec2: 2, jam: false },
        },
        { label: 'Second pair in: count complete, 4-pack strokes out', holdMs: 1300, expect: { Y1: true } },
        {
          label: '4-pack delivered to the lift: pusher springs home',
          holdMs: 700,
          expect: { Y1: false },
          expectMachine: { liftLoad: 4, sec2: 0, jam: false },
        },
        {
          label: 'Next pair stages, but no second 4-pack push',
          holdMs: 1100,
          expect: { Y1: false },
          expectMachine: { sec2: 2, liftLoad: 4, jam: false },
        },
      ],
    },
    {
      name: 'Machine starts empty: everything rests',
      steps: [{ label: 'Lanes still filling, no strokes', holdMs: 900, expect: { Y0: false, Y1: false } }],
    },
  ],
};
