import type { PuzzleSpec } from '../types.js';

export const packLift: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pack-lift',
  title: 'Packer: Lift & Flip',
  difficulty: 'hard',
  order: 23,
  category: 'packaging',
  summary: 'Flip each loaded 4-pack over into section 3 — four flips build the 16-pack.',
  briefing: [
    'The LIFT (Y2, sensors DOWN X4 / UP X5) is a flipper: drive it up with a 4-pack',
    'on the tray and it tips the group over the wall into section 3, where the',
    'cartons land standing ON END. Each flip shoves the previous column along, so',
    'four flips stack a 4×4 block of 16. (The retaining bracket that keeps the',
    'tippy on-end stack from falling is parked forward for you in this puzzle.)',
    '',
    'Keep the whole front end from the previous puzzles running (pair strokes,',
    'stroke counter, 4-pack load) and add the flip cycle:',
    '',
    '  1. When the 4-pack pusher reaches OUT (X3), the group is on the tray:',
    '     latch a flip request (SET M0) and drive Y2 from it.',
    '  2. The lift physically refuses to rise while the 4-pack rod is still under',
    '     the tray. Hold Y2 on and it will go as soon as the rod clears X2.',
    '  3. At the top (X5) the load tips over into section 3: release the latch',
    '     (RST M0) so the lift comes back down ready for the next group.',
    '',
    'Let it run: the machine should flip group after group without a jam.',
  ].join('\n'),
  hints: [
    'Three new rungs on top of the 4-pack solution: X3 → SET M0, then M0 → Y2, then',
    'X5 → RST M0.',
    'Latching off X3 matters: it is only true for a moment while the 4-pack pusher is',
    'out, but the flip takes much longer — an unlatched X3 → Y2 drops the lift the',
    'moment the pusher springs home.',
    'No extra interlock is needed for the rise itself: the machine holds the lift at',
    'the bottom until the 4-pack rod is home, as long as Y2 stays commanded.',
  ],
  devices: [
    { address: 'X14', label: 'Box at Stop (near)', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Box at Stop (far)', io: 'input', widget: 'sensor' },
    { address: 'X0', label: '2-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X1', label: '2-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X2', label: '4-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X3', label: '4-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'Lift Down', io: 'input', widget: 'sensor' },
    { address: 'X5', label: 'Lift Up', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: '2-Pack Pusher', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: '4-Pack Pusher', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y2', label: 'Lift / Flipper', io: 'output', widget: 'motor', color: '#a78bfa' },
  ],
  registers: [
    { address: 'C0', label: 'Pair-stroke counter', note: 'preset K2 — two strokes = one 4-pack' },
    { address: 'M0', label: 'Flip in progress' },
  ],
  allowedInstructions: ['contact-no', 'contact-nc', 'coil-out', 'coil-set', 'coil-reset', 'counter'],
  maxRungs: 9,
  processId: 'packaging',
  scenarios: [
    {
      name: 'Loaded 4-packs flip over into section 3',
      steps: [
        {
          label: 'First 4-pack loads onto the lift',
          holdMs: 4600,
          expect: { Y2: true },
          expectMachine: { liftLoad: 4, jam: false },
        },
        {
          label: 'Flip! Four cartons land on end in section 3',
          holdMs: 1400,
          expect: { Y2: false },
          expectMachine: { sec3: 4, liftLoad: 0, jam: false },
        },
        { label: 'Lift back down, ready for the next group', holdMs: 900, expect: { X4: true } },
        {
          label: 'Second flip lands — eight cartons staged',
          holdMs: 2400,
          expectMachine: { sec3: 8, jam: false },
        },
      ],
    },
    {
      name: 'Machine starts empty — everything rests',
      steps: [
        { label: 'Lanes still filling: no strokes, lift stays down', holdMs: 900, expect: { Y0: false, Y1: false, Y2: false, X4: true } },
      ],
    },
  ],
};
