import type { PuzzleSpec } from '../types.js';

export const packBatch: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pack-batch',
  title: 'Packer: Automatic Carton Batch',
  difficulty: 'hard',
  order: 24,
  category: 'packaging',
  summary: 'Run the full auto packer: hold, repeat-push three fed cartons, count them, then finish.',
  briefing: [
    'The finished machine. With cartons feeding on the conveyor, the packer runs on',
    'its own: the BACK-STOP (Y5) goes forward to guard the deck, then the 2-PACK',
    'PUSHER (Y0) strokes once per carton. After THREE cartons are packed the batch is',
    'done — the back-stop releases and the BATCH DONE lamp (Y6) latches until RESET.',
    '',
    'Cycle, once START (X20) begins it:',
    '  • Back-stop FORWARD (Y5) to X13.',
    '  • While a carton is queued on the belt (X16) and fewer than 3 are packed,',
    '    stroke the pusher: OUT (Y0) to X1, retract to X0 — counting each stroke.',
    '    No carton queued? The pusher waits, back-stop still forward.',
    '  • On the 3rd count: release the back-stop (X12) and latch BATCH DONE (Y6).',
    '  • RESET (X22) clears the count and the lamp for the next batch.',
    '',
    'Sensors: pusher IN (X0)/OUT (X1); back-stop BACK (X12)/FORWARD (X13); carton',
    'queued on belt (X16). Use a counter with preset K3.',
  ].join('\n'),
  hints: [
    'Cycle latch: SET M0 on START; RESET M0 on the BATCH DONE lamp Y6. Back-stop',
    'Y5 = M0, so it releases the instant the batch finishes.',
    'Reciprocate the pusher with one step latch M1: SET M1 on (X0 · M0 · X13 · C0(NC)',
    '· X16) — home, cycle active, guarded, not yet at 3, carton present — and RESET',
    'M1 on X1 (reached out). Y0 = M1.',
    'Count strokes: a normally-open X1 contact drives counter C0 (K3); it ticks once',
    'per stroke as the pusher hits OUT.',
    'Finish: SET Y6 on (C0 · X0) — three counted and pusher home. RESET Y6 and RESET',
    'C0 both on X22.',
  ],
  devices: [
    { address: 'X20', label: 'Start', io: 'input', widget: 'momentary' },
    { address: 'X22', label: 'Reset', io: 'input', widget: 'momentary' },
    { address: 'X16', label: 'Carton Queued', io: 'input', widget: 'toggle' },
    { address: 'X0', label: 'Pusher In', io: 'input', widget: 'sensor' },
    { address: 'X1', label: 'Pusher Out', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Back-Stop Back', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'Back-Stop Forward', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: '2-Pack Pusher', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y5', label: 'Back-Stop', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y6', label: 'Batch Done', io: 'output', widget: 'lamp', color: '#22c55e' },
  ],
  registers: [
    { address: 'M0', label: 'Cycle active', note: 'set by START, cleared when the batch finishes' },
    { address: 'M1', label: 'Pusher stroke', note: 'reciprocates the pusher, one stroke per carton' },
    { address: 'C0', label: 'Carton count', note: 'preset K3, reset by X22' },
  ],
  allowedInstructions: ['contact-no', 'contact-nc', 'coil-out', 'coil-set', 'coil-reset', 'counter'],
  maxRungs: 12,
  processId: 'packaging',
  scenarios: [
    {
      name: 'Packs three cartons then finishes',
      steps: [
        {
          label: 'Cartons feeding, tap Start — back-stop goes forward',
          setInputs: { X16: true, X20: true },
          holdMs: 100,
          expect: { Y5: true, Y0: false, Y6: false },
        },
        {
          label: 'Back-stop forward — first stroke begins',
          setInputs: { X20: false },
          holdMs: 400,
          expect: { Y0: true, Y5: true, Y6: false },
        },
        {
          label: 'Two cartons in — still not done',
          holdMs: 1800,
          expect: { Y6: false, Y5: true },
        },
        {
          label: 'Third carton packed — batch finishes, back-stop releases',
          holdMs: 2200,
          expect: { Y6: true, Y5: false, Y0: false },
        },
        { label: 'Press Reset — lamp clears', setInputs: { X22: true }, holdMs: 100, expect: { Y6: false } },
      ],
    },
    {
      name: 'Pauses when no carton is queued',
      steps: [
        {
          label: 'Start with an empty belt — back-stop still readies',
          setInputs: { X16: false, X20: true },
          holdMs: 100,
          expect: { Y5: true },
        },
        {
          label: 'No carton — pusher waits',
          setInputs: { X20: false },
          holdMs: 500,
          expect: { Y0: false, Y5: true },
        },
        {
          label: 'A carton arrives — pusher strokes',
          setInputs: { X16: true },
          holdMs: 400,
          expect: { Y0: true },
        },
      ],
    },
  ],
};
