import type { PuzzleSpec } from '../types.js';

export const packFull: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pack-full',
  title: 'Packer: Ship the 16-Pack',
  difficulty: 'hard',
  order: 24,
  category: 'packaging',
  summary: 'The capstone: run the whole line and ship a finished 16-pack to the out-feed.',
  briefing: [
    'The full line, end to end. Everything from the earlier work orders keeps running:',
    'pairs into section 2, 4-packs onto the lift, flips into section 3. Now the',
    'retaining bracket is yours to control, and a finished 16-pack has to be shipped',
    'to the out-feed.',
    '',
    '## Equipment',
    '- Y5 RETAINING BRACKET, with sensors X12 BACK and X13 FORWARD. It is the',
    '  counter-hold that backs the tippy on-end stack in section 3.',
    '- Y3 16-PACK-1 pusher (X6 IN, X7 OUT): slides the finished block into section 4.',
    '- Y4 16-PACK-2 pusher (X10 IN, X11 OUT): rides the pack away on the out-feed belt.',
    '- C1 flip counter (preset K4) and step relays M1 to M5 (see Working Registers).',
    '',
    '## Sequence of operation',
    '1. Drive the bracket forward from the start, and keep it there whenever a flip',
    '   can land.',
    '2. Count the flips on C1. Four flips means 16 cartons are staged in section 3.',
    '3. Wait for the lift to settle back down (X4), then run the shipping sequence one',
    '   step at a time:',
    '   a. Bracket BACK (drop Y5) until X12.',
    '   b. 16-PACK-1 (Y3) full stroke out to X7, then let it spring home to X6.',
    '   c. Bracket FORWARD again: the next pack\'s flips need it in place.',
    '   d. 16-PACK-2 (Y4) full stroke out to X11, then home to X10.',
    '4. Reset C1 as the sequence starts, so flips for the next 16-pack count from zero,',
    '   then wait for the next group.',
    '',
    '## Interlocks and safety',
    '- A flip landing while the bracket is not FORWARD tips the on-end cartons over.',
    '- The 16-PACK-1 plate sweeps right across the bracket\'s line, so pushing while',
    '  the bracket is forward is a crash.',
    '- Those two rules pull in opposite directions, which is exactly why the shipping',
    '  steps are ordered as they are. Drive them as one-hot step relays and advance on',
    '  each step\'s own end sensor.',
    '- The front end keeps feeding while this pack ships, so gate the flip output too.',
    '  The lift simply waits at the bottom until the window closes.',
    '',
    '## Acceptance',
    '- Ship one finished 16-pack to the out-feed without a jam.',
    '- Full marks also want pace: the pack should ship in 19.5 s. That only happens if',
    '  the front end keeps grouping cartons while the lift is away, so the next four',
    '  are already waiting when it comes back down.',
  ].join('\n'),
  hints: [
    'Let the bracket rest forward: Y5 = M1(NC) · M2(NC) · M3(NC). It pulls back only ' +
      'across the steps that need it and springs forward again by itself.',
    'Start the sequence on the lift settling with the count complete: a RISING X4 ' +
      'contact in series with C1 → SET M1, and reset C1 on the same condition.',
    'Each hand-off is "step relay AND its end sensor": M1·X12 → SET M2 / RST M1; ' +
      'M2·X7 → SET M3 / RST M2; M3·X6 → SET M4 / RST M3; M4·X11 → SET M5 / RST M4; ' +
      'M5·X10 → RST M5. The pushers are momentary: Y3 = M2, Y4 = M4.',
    'The front end keeps flipping while this pack ships, so gate the flip output (Y2 = ' +
      'M0 · M1(NC) · M2(NC) · M3(NC)) so no flip can land while the bracket is away. ' +
      'The lift just waits at the bottom until the window closes.',
  ],
  devices: [
    { address: 'X14', label: 'Box at Stop (near)', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Box at Stop (far)', io: 'input', widget: 'sensor' },
    { address: 'X16', label: 'Box in Queue (near)', io: 'input', widget: 'sensor' },
    { address: 'X17', label: 'Box in Queue (far)', io: 'input', widget: 'sensor' },
    { address: 'X0', label: '2-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X1', label: '2-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X2', label: '4-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X3', label: '4-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'Lift Down', io: 'input', widget: 'sensor' },
    { address: 'X5', label: 'Lift Up', io: 'input', widget: 'sensor' },
    { address: 'X6', label: '16-Pack-1 In', io: 'input', widget: 'sensor' },
    { address: 'X7', label: '16-Pack-1 Out', io: 'input', widget: 'sensor' },
    { address: 'X10', label: '16-Pack-2 In', io: 'input', widget: 'sensor' },
    { address: 'X11', label: '16-Pack-2 Out', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Bracket Back', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'Bracket Forward', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: '2-Pack Pusher', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: '4-Pack Pusher', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y2', label: 'Lift / Flipper', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y3', label: '16-Pack Pusher 1', io: 'output', widget: 'motor', color: '#22c55e' },
    { address: 'Y4', label: '16-Pack Pusher 2', io: 'output', widget: 'motor', color: '#f472b6' },
    { address: 'Y5', label: 'Retaining Bracket', io: 'output', widget: 'motor', color: '#fb923c' },
  ],
  registers: [
    { address: 'C0', label: 'Pair-stroke counter', note: 'preset K2: two strokes = one 4-pack' },
    { address: 'C1', label: 'Flip counter', note: 'preset K4: four flips = one 16-pack' },
    { address: 'M0', label: 'Flip in progress' },
    { address: 'M1', label: 'Ship step 1: bracket back' },
    { address: 'M2', label: 'Ship step 2: 16-pack-1 out' },
    { address: 'M3', label: 'Ship step 3: 16-pack-1 home' },
    { address: 'M4', label: 'Ship step 4: 16-pack-2 out' },
    { address: 'M5', label: 'Ship step 5: 16-pack-2 home' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'contact-rising',
    'coil-out',
    'coil-set',
    'coil-reset',
    'counter',
  ],
  maxRungs: 22,
  processId: 'packaging',
  scenarios: [
    {
      name: 'Ship a finished 16-pack, end to end',
      // Sixteen cartons through four flips and out. The line is only this quick
      // if the front end keeps grouping while the lift is away: hold the 2-pack
      // pusher until the lift is back down and every flip lands a second late.
      parMs: 19500,
      steps: [
        {
          label: 'First 4-pack flips into section 3',
          until: { machine: { sec3: 4 } },
          holdMs: 12000,
          expectMachine: { jam: false },
        },
        {
          label: 'Second flip lands',
          until: { machine: { sec3: 8 } },
          holdMs: 9000,
          expectMachine: { jam: false },
        },
        {
          label: 'Fourth flip: 16 cartons staged in section 3',
          until: { machine: { sec3: 16 } },
          holdMs: 16000,
          expectMachine: { jam: false },
        },
        {
          label: 'The bracket is fully back before the 16-pack pusher moves',
          until: { bits: { Y3: true } },
          holdMs: 6000,
          expect: { X12: true, Y5: false },
        },
        {
          label: 'The block is squared into section 4',
          until: { machine: { sec4: 16 } },
          holdMs: 4000,
          expectMachine: { sec3: 0, jam: false },
        },
        {
          label: '16-pack-1 springs home and the bracket comes forward again',
          until: { bits: { X6: true, Y5: true } },
          holdMs: 4000,
          expect: { Y3: false },
        },
        {
          label: '16-pack-2 ships it: one finished 16-pack on the out-feed',
          until: { machine: { finished: 1 } },
          holdMs: 5000,
          thenHoldMs: 400,
          expect: { Y4: false, Y5: true },
          expectMachine: { sec4: 0, jam: false },
        },
      ],
    },
    {
      name: 'Power-up: bracket forward, everything else rests',
      steps: [
        {
          label: 'Lanes still filling: only the retaining bracket moves',
          holdMs: 600,
          expect: { Y0: false, Y1: false, Y2: false, Y3: false, Y4: false, Y5: true, X13: true },
        },
      ],
    },
  ],
};
