import type { PuzzleSpec } from '../types.js';

export const packFull: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pack-full',
  title: 'Packer: Ship the 16-Pack',
  difficulty: 'hard',
  order: 24,
  category: 'packaging',
  summary: 'The capstone: run the whole line and ship a finished 16-pack to the out-feed.',
  briefing: [
    'The full line, end to end. Everything from the earlier puzzles keeps running —',
    'pairs into section 2, 4-packs onto the lift, flips into section 3 — and now the',
    'back end ships the product:',
    '',
    '  1. Count the flips on C1 (preset K4): four flips = 16 boxes in section 3.',
    '  2. Wait for the lift to settle back down (X4) before touching the pack —',
    '     then run the shipping sequence, one step at a time:',
    '       a. BACK-STOP forward (Y5) until X13. It guards section 4\'s open side.',
    '       b. 16-PACK-1 (Y3) full stroke to X7 — the pack slides into section 4',
    '          against the stop — then let it spring home to X6.',
    '       c. Back-stop back (Y5 off) until X12: the pack is released.',
    '       d. 16-PACK-2 (Y4) full stroke to X11 — the pack ships to the finished',
    '          station — then home to X10. Done: reset and wait for the next 16.',
    '',
    'Order is everything: push before the stop is forward and the pack slides out',
    'the open side; ship before the stop is back and you crush the pack against it.',
    'Drive the sequence as one-hot step relays (M1..M6), advance on each step\'s end',
    'sensor, and reset C1 as the sequence starts so flips for the NEXT 16-pack count',
    'from zero. Ship one finished 16-pack without a jam.',
  ].join('\n'),
  hints: [
    'Start the sequence on the lift settling with the count complete: a RISING X4',
    'contact in series with C1 → SET M1, and reset C1 on the same condition.',
    'Each hand-off is "step relay AND its end sensor": M1·X13 → SET M2 / RST M1;',
    'M2·X7 → SET M3 / RST M2; M3·X6 → SET M4 / RST M3; M4·X12 → SET M5 / RST M4;',
    'M5·X11 → SET M6 / RST M5; M6·X10 → RST M6.',
    'The back-stop must stay forward across steps 1-3: Y5 = M1 ∥ M2 ∥ M3. The two',
    'pushers are momentary: Y3 = M2, Y4 = M5 — dropping the relay springs them home.',
    'The front end is untouched: the flips that build the NEXT 16-pack keep landing',
    'in section 3 while this one ships.',
  ],
  devices: [
    { address: 'X20', label: 'Belt Run', io: 'input', widget: 'toggle' },
    { address: 'X14', label: 'Box at Stop (near)', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Box at Stop (far)', io: 'input', widget: 'sensor' },
    { address: 'X16', label: 'Box in Queue (near)', io: 'input', widget: 'sensor' },
    { address: 'X17', label: 'Box in Queue (far)', io: 'input', widget: 'sensor' },
    { address: 'X0', label: '2-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X1', label: '2-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X2', label: '4-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X3', label: '4-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'Lift Down', io: 'input', widget: 'sensor' },
    { address: 'X5', label: 'Lift Up', io: 'input', widget: 'sensor' },
    { address: 'X6', label: '16-Pack-1 In', io: 'input', widget: 'sensor' },
    { address: 'X7', label: '16-Pack-1 Out', io: 'input', widget: 'sensor' },
    { address: 'X10', label: '16-Pack-2 In', io: 'input', widget: 'sensor' },
    { address: 'X11', label: '16-Pack-2 Out', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Back-Stop Back', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'Back-Stop Forward', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: '2-Pack Pusher', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: '4-Pack Pusher', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y2', label: 'Lift / Flipper', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y3', label: '16-Pack Pusher 1', io: 'output', widget: 'motor', color: '#22c55e' },
    { address: 'Y4', label: '16-Pack Pusher 2', io: 'output', widget: 'motor', color: '#f472b6' },
    { address: 'Y5', label: 'Back-Stop', io: 'output', widget: 'motor', color: '#fb923c' },
  ],
  registers: [
    { address: 'C0', label: 'Pair-stroke counter', note: 'preset K2 — two strokes = one 4-pack' },
    { address: 'C1', label: 'Flip counter', note: 'preset K4 — four flips = one 16-pack' },
    { address: 'M0', label: 'Flip in progress' },
    { address: 'M1', label: 'Ship step 1 — back-stop forward' },
    { address: 'M2', label: 'Ship step 2 — 16-pack-1 out' },
    { address: 'M3', label: 'Ship step 3 — 16-pack-1 home' },
    { address: 'M4', label: 'Ship step 4 — back-stop back' },
    { address: 'M5', label: 'Ship step 5 — 16-pack-2 out' },
    { address: 'M6', label: 'Ship step 6 — 16-pack-2 home' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'contact-rising',
    'coil-out',
    'coil-set',
    'coil-reset',
    'counter',
  ],
  maxRungs: 22,
  processId: 'packaging',
  scenarios: [
    {
      name: 'Ship a finished 16-pack, end to end',
      steps: [
        {
          label: 'First 4-pack flips into section 3',
          setInputs: { X20: true },
          holdMs: 5600,
          expectMachine: { sec3: 4, jam: false },
        },
        { label: 'Second flip lands', holdMs: 3700, expectMachine: { sec3: 8, jam: false } },
        { label: 'Fourth flip — 16 boxes staged', holdMs: 6200, expectMachine: { sec3: 16, jam: false } },
        {
          label: 'Back-stop forward, 16-pack-1 pushes the pack across',
          holdMs: 1000,
          expect: { Y5: true, Y3: true },
        },
        {
          label: 'Pack squared into section 4, pusher home again',
          holdMs: 800,
          expect: { Y3: false },
          expectMachine: { sec4: 16, jam: false },
        },
        {
          label: 'Back-stop released, 16-pack-2 ships it — one finished 16-pack',
          holdMs: 1500,
          expect: { Y4: false },
          expectMachine: { finished: 1, sec4: 0, jam: false },
        },
      ],
    },
    {
      name: 'Belt off — the whole line rests',
      steps: [
        {
          label: 'No boxes, nothing moves',
          holdMs: 500,
          expect: { Y0: false, Y1: false, Y2: false, Y3: false, Y4: false, Y5: false },
        },
      ],
    },
  ],
};
