import type { PuzzleSpec } from '../types.js';

export const packFull: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pack-full',
  title: 'Packer: Ship the 16-Pack',
  difficulty: 'hard',
  order: 24,
  category: 'packaging',
  summary: 'The capstone: run the whole line and ship a finished 16-pack to the out-feed.',
  briefing: [
    'The full line, end to end. Everything from the earlier puzzles keeps running —',
    'pairs into section 2, 4-packs onto the lift, flips into section 3 — but the',
    'RETAINING BRACKET (Y5, sensors BACK X12 / FORWARD X13) is now yours to control.',
    'It is the counter-hold that backs the tippy on-end stack: a flip landing while',
    'it is not FORWARD tips the cartons over. Drive it forward from the start and',
    'keep it there whenever flips can land.',
    '',
    'Then ship the product:',
    '',
    '  1. Count the flips on C1 (preset K4): four flips = 16 cartons in section 3.',
    '  2. Wait for the lift to settle back down (X4), then run the shipping',
    '     sequence, one step at a time:',
    '       a. Bracket BACK (drop Y5) until X12 — the 16-PACK-1 plate sweeps right',
    '          across the bracket\'s line, so pushing while it is forward is a crash.',
    '       b. 16-PACK-1 (Y3) full stroke to X7 — the block slides into section 4 —',
    '          then let it spring home to X6.',
    '       c. Y5 forward again: the next pack\'s flips need the bracket in place.',
    '       d. 16-PACK-2 (Y4) full stroke to X11 — the pack rides the out-feed belt',
    '          away — then home to X10. Done: reset and wait for the next 16.',
    '',
    'Order is everything: push with the bracket forward and the plate crashes into',
    'it; let a flip land while it is back and the stack tips. Drive the sequence',
    'as one-hot step relays (M1..M5), advance on each step\'s end sensor, and reset',
    'C1 as the sequence starts so flips for the NEXT 16-pack count from zero. Ship',
    'one finished 16-pack without a jam.',
  ].join('\n'),
  hints: [
    'Let the bracket rest forward: Y5 = M1(NC) · M2(NC) · M3(NC) — it pulls back',
    'only across the steps that need it and springs forward again by itself.',
    'Start the sequence on the lift settling with the count complete: a RISING X4',
    'contact in series with C1 → SET M1, and reset C1 on the same condition.',
    'Each hand-off is "step relay AND its end sensor": M1·X12 → SET M2 / RST M1;',
    'M2·X7 → SET M3 / RST M2; M3·X6 → SET M4 / RST M3; M4·X11 → SET M5 / RST M4;',
    'M5·X10 → RST M5. The pushers are momentary: Y3 = M2, Y4 = M4.',
    'The front end keeps flipping while this pack ships — gate the flip output',
    '(Y2 = M0 · M1(NC) · M2(NC) · M3(NC)) so no flip can land while the bracket is',
    'away. The lift just waits at the bottom until the window closes.',
  ],
  devices: [
    { address: 'X14', label: 'Box at Stop (near)', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Box at Stop (far)', io: 'input', widget: 'sensor' },
    { address: 'X16', label: 'Box in Queue (near)', io: 'input', widget: 'sensor' },
    { address: 'X17', label: 'Box in Queue (far)', io: 'input', widget: 'sensor' },
    { address: 'X0', label: '2-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X1', label: '2-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X2', label: '4-Pack In', io: 'input', widget: 'sensor' },
    { address: 'X3', label: '4-Pack Out', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'Lift Down', io: 'input', widget: 'sensor' },
    { address: 'X5', label: 'Lift Up', io: 'input', widget: 'sensor' },
    { address: 'X6', label: '16-Pack-1 In', io: 'input', widget: 'sensor' },
    { address: 'X7', label: '16-Pack-1 Out', io: 'input', widget: 'sensor' },
    { address: 'X10', label: '16-Pack-2 In', io: 'input', widget: 'sensor' },
    { address: 'X11', label: '16-Pack-2 Out', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Bracket Back', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'Bracket Forward', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: '2-Pack Pusher', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: '4-Pack Pusher', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y2', label: 'Lift / Flipper', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y3', label: '16-Pack Pusher 1', io: 'output', widget: 'motor', color: '#22c55e' },
    { address: 'Y4', label: '16-Pack Pusher 2', io: 'output', widget: 'motor', color: '#f472b6' },
    { address: 'Y5', label: 'Retaining Bracket', io: 'output', widget: 'motor', color: '#fb923c' },
  ],
  registers: [
    { address: 'C0', label: 'Pair-stroke counter', note: 'preset K2 — two strokes = one 4-pack' },
    { address: 'C1', label: 'Flip counter', note: 'preset K4 — four flips = one 16-pack' },
    { address: 'M0', label: 'Flip in progress' },
    { address: 'M1', label: 'Ship step 1 — bracket back' },
    { address: 'M2', label: 'Ship step 2 — 16-pack-1 out' },
    { address: 'M3', label: 'Ship step 3 — 16-pack-1 home' },
    { address: 'M4', label: 'Ship step 4 — 16-pack-2 out' },
    { address: 'M5', label: 'Ship step 5 — 16-pack-2 home' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'contact-rising',
    'coil-out',
    'coil-set',
    'coil-reset',
    'counter',
  ],
  maxRungs: 22,
  processId: 'packaging',
  scenarios: [
    {
      name: 'Ship a finished 16-pack, end to end',
      steps: [
        {
          label: 'First 4-pack flips into section 3',
          holdMs: 6000,
          expectMachine: { sec3: 4, jam: false },
        },
        { label: 'Second flip lands', holdMs: 3300, expectMachine: { sec3: 8, jam: false } },
        { label: 'Fourth flip — 16 cartons staged', holdMs: 7000, expectMachine: { sec3: 16, jam: false } },
        {
          label: 'Bracket pulls back, 16-pack-1 slides the block across',
          holdMs: 1000,
          expect: { Y3: true, Y5: false },
        },
        {
          label: 'Block squared into section 4, pusher home again',
          holdMs: 700,
          expect: { Y3: false },
          expectMachine: { sec4: 16, jam: false },
        },
        {
          label: 'Bracket forward again, 16-pack-2 ships it — one finished 16-pack',
          holdMs: 1500,
          expect: { Y4: false, Y5: true },
          expectMachine: { finished: 1, sec4: 0, jam: false },
        },
      ],
    },
    {
      name: 'Power-up: bracket forward, everything else rests',
      steps: [
        {
          label: 'Lanes still filling — only the retaining bracket moves',
          holdMs: 600,
          expect: { Y0: false, Y1: false, Y2: false, Y3: false, Y4: false, Y5: true, X13: true },
        },
      ],
    },
  ],
};
