import type { PuzzleSpec } from '../types.js';

export const pickPlaceCycle: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pick-place-cycle',
  title: 'Pick & Place: One Cycle',
  difficulty: 'hard',
  order: 25,
  category: 'pick-place',
  summary: 'Sequence swing, reach and grip into one repeating pick-and-place cycle.',
  briefing: [
    'A single robot arm swings between an INFEED station and one TRAY SLOT. With',
    'nothing else commanding it, it must repeatedly:',
    '',
    '  1. At the infeed, lower the REACH (Y2) down onto the part.',
    '  2. Once the reach is DOWN (X10), close the GRIPPER (Y3).',
    '  3. Once GRIPPED (X12), raise the reach back up.',
    '  4. Once fully retracted (X11), swing the arm to the tray (Y0).',
    '  5. At the slot, lower the reach again and open the gripper to release.',
    '  6. Once the slot senses OCCUPIED (X14), retract and swing back (Y1).',
    '',
    'The slot only holds one part. Once it is occupied, do not lower the reach or',
    'close the gripper again — park the arm, retracted, at the infeed instead of',
    'trying to deliver a second part on top of the first.',
    '',
    'X10 (Reach Down), X11 (Reach Up), X12 (Gripped) and X14 (Slot Occupied) are field',
    'sensors driven by the machine, so you cannot press them; neither are X0 (At',
    'Infeed) and X1 (At Slot), which the swing axis reports on its own.',
  ].join('\n'),
  hints: [
    'Latch a Carrying bit M0: SET it on a rising edge of X12 (just gripped), RESET it',
    'on a rising edge of X14 (just placed).',
    'Reach (Y2) has two SET conditions ORed together: at the infeed with nothing',
    'carried and the slot still free, or at the slot while carrying. RESET it on',
    'rise(X12) OR rise(X14) — whichever goal was just reached, retract.',
    'Gripper (Y3): SET at the infeed once reach is down and not yet carrying (and the',
    'slot is free); RESET at the slot once reach is down and carrying.',
    'Swing out (Y0): SET while carrying and fully retracted. RESET on arrival (X1).',
    'Swing home (Y1) mirrors it: SET while not carrying and fully retracted, RESET on',
    'arrival (X0).',
  ],
  devices: [
    { address: 'X0', label: 'At Infeed', io: 'input', widget: 'sensor' },
    { address: 'X1', label: 'At Slot', io: 'input', widget: 'sensor' },
    { address: 'X10', label: 'Reach Down', io: 'input', widget: 'sensor' },
    { address: 'X11', label: 'Reach Up', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Gripped', io: 'input', widget: 'sensor' },
    { address: 'X14', label: 'Slot Occupied', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: 'Swing to Tray', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: 'Swing to Infeed', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y2', label: 'Reach Down', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y3', label: 'Gripper Close', io: 'output', widget: 'motor', color: '#f59e0b' },
  ],
  registers: [
    { address: 'M0', label: 'Carrying', note: 'set on rise(X12), reset on rise(X14)' },
  ],
  allowedInstructions: ['contact-no', 'contact-nc', 'contact-rising', 'coil-out', 'coil-set', 'coil-reset'],
  maxRungs: 12,
  processId: 'pickPlace',
  scenarios: [
    {
      name: 'Full automatic pick-and-place cycle',
      steps: [
        {
          label: 'Reach lowers at the infeed before the gripper closes',
          holdMs: 200,
          expect: { Y2: true, Y3: false },
        },
        {
          label: 'Gripper closes once reach bottoms out',
          holdMs: 1000,
          expect: { Y3: true },
        },
        {
          label: 'Full stroke: part is picked, swung across, and placed in the slot',
          holdMs: 3800,
          expectMachine: { placed: 1, jam: false },
          expect: { X14: true },
        },
        {
          label: 'Slot is full — arm idles retracted at the infeed instead of overfilling',
          holdMs: 4000,
          expectMachine: { placed: 1, jam: false },
          expect: { Y2: false, Y3: false, X0: true },
        },
      ],
    },
  ],
};
