import type { PuzzleSpec } from '../types.js';

export const pickPlaceTray: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pick-place-tray',
  title: 'Pick & Place: Fill the Tray',
  difficulty: 'hard',
  order: 26,
  category: 'pick-place',
  summary: 'Generalize the cycle to 4 slots, counting placements until the tray is full.',
  briefing: [
    'The tray now has FOUR slots (sensed at X1-X4, occupied lamps at X14-X17). The arm',
    'should keep swinging outward past any slot that is already occupied and stop at',
    'the first one that is still free — the same reach/grip/swing cycle as before,',
    "just no longer aimed at a single fixed slot.",
    '',
    'Count each placement on a counter (C0, preset K4). Once four parts have been',
    'placed, light the TRAY FULL lamp (Y4) and stop attempting new picks — park the',
    'arm retracted at the infeed.',
  ].join('\n'),
  hints: [
    "Reach/gripper at the infeed still gate on \"not carrying\", but the overfill guard",
    'is now nc(C0) instead of a single occupied sensor.',
    'Reach/gripper at a slot fire on carrying AND (at slot 1 OR 2 OR 3 OR 4) — only one',
    'of those sensors is ever true at once, so the OR needs no further gating.',
    'Swing out (Y0) still just needs carrying + fully retracted; it keeps running',
    'until an occupied-slot check stops it. RESET Y0 on [X1·NOT X14] OR [X2·NOT X15]',
    'OR [X3·NOT X16] OR [X4·NOT X17] — arriving at an EMPTY slot is what stops it, so',
    'a full slot is sailed straight past.',
    'Pulse a placed-flag on any rising occupied sensor (X14-X17); use it to RESET the',
    'Carrying latch and to drive counter C0. Light Y4 from C0 having reached its',
    'preset.',
  ],
  devices: [
    { address: 'X0', label: 'At Infeed', io: 'input', widget: 'sensor' },
    { address: 'X1', label: 'At Slot 1', io: 'input', widget: 'sensor' },
    { address: 'X2', label: 'At Slot 2', io: 'input', widget: 'sensor' },
    { address: 'X3', label: 'At Slot 3', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'At Slot 4', io: 'input', widget: 'sensor' },
    { address: 'X10', label: 'Reach Down', io: 'input', widget: 'sensor' },
    { address: 'X11', label: 'Reach Up', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Gripped', io: 'input', widget: 'sensor' },
    { address: 'X14', label: 'Slot 1 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Slot 2 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X16', label: 'Slot 3 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X17', label: 'Slot 4 Occupied', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: 'Swing to Tray', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: 'Swing to Infeed', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y2', label: 'Reach Down', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y3', label: 'Gripper Close', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y4', label: 'Tray Full', io: 'output', widget: 'lamp', color: '#22c55e' },
  ],
  registers: [
    { address: 'M0', label: 'Carrying', note: 'set on rise(X12), reset on any placement pulse' },
    { address: 'C0', label: 'Placed count', note: 'preset K4 — counts placements, drives Y4' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'contact-rising',
    'coil-out',
    'coil-set',
    'coil-reset',
    'counter',
  ],
  maxRungs: 16,
  processId: 'pickPlace',
  scenarios: [
    {
      name: 'Four cycles fill the tray, then the arm idles',
      steps: [
        {
          label: 'First part placed in slot 1',
          holdMs: 4500,
          expectMachine: { placed: 1, jam: false },
          expect: { X14: true },
        },
        {
          label: 'Second part placed in slot 2, sailing past slot 1',
          holdMs: 6000,
          expectMachine: { placed: 2, jam: false },
          expect: { X15: true },
        },
        {
          label: 'Third part placed in slot 3',
          holdMs: 7500,
          expectMachine: { placed: 3, jam: false },
          expect: { X16: true },
        },
        {
          label: 'Fourth part placed in slot 4 — tray full lamp lights',
          holdMs: 9000,
          expectMachine: { placed: 4, jam: false },
          expect: { X17: true, Y4: true },
        },
        {
          label: 'Tray stays full — arm idles instead of attempting a fifth pick',
          holdMs: 5000,
          expectMachine: { placed: 4, jam: false },
          expect: { Y2: false, Y3: false, X0: true, Y4: true },
        },
      ],
    },
  ],
};
