import type { PuzzleSpec } from '../types.js';

export const pickPlaceTray: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pick-place-tray',
  title: 'Pick & Place: Load the Tray',
  difficulty: 'hard',
  order: 26,
  category: 'pick-place',
  summary: 'Serve four tray pads, skip occupied ones, and stop when the tray is full.',
  briefing: [
    'The tray has been extended to FOUR pads fanned out along the swing arc.',
    'Arrival sensors X1 to X4 report which pad the arm is over, and occupancy',
    'sensors X14 to X17 report which pads hold a part. The tray also provides a',
    'combined Tray Full sensor (X18) that turns on once all four pads are occupied.',
    '',
    'Operating procedure:',
    '',
    '  1. Pick at the infeed exactly as in the first work order.',
    '  2. Swing outward (Y0) and deliver the part to the FIRST free pad:',
    '     a. Arriving over an occupied pad: keep swinging, do not stop.',
    '     b. Arriving over a free pad: stop, lower, release, retract.',
    '  3. Swing home (Y1) and repeat with the next part.',
    '  4. When X18 turns on: light the TRAY FULL lamp (Y4), stop picking, and park',
    '     the arm retracted at the infeed.',
    '',
    'Safety notes:',
    '',
    '  1. Releasing a part over an occupied pad jams the cell. The stop-at-first-',
    '     free rule in step 2 is what prevents it.',
    '  2. The mid-air release and swing interlock rules from the first work order',
    '     still apply.',
  ].join('\n'),
  hints: [
    'Keep the single-slot rungs and generalize them. The infeed pick guard changes ' +
      'from nc(X14) to nc(X18): pick only while the tray is not yet full.',
    'Make one placement pulse M1 that covers every pad: OR the rising edges of X14 ' +
      'to X17 into a single coil with vertical links. RESET the Carrying latch on M1.',
    'Stop the swing at the first FREE pad: RESET Y0 on (X1 and nc X14) or (X2 and ' +
      'nc X15) or (X3 and nc X16) or (X4 and nc X17). An occupied pad never matches ' +
      'its branch, so the arm sails straight past it.',
    'The place rungs OR across pads: reach down at pad N while carrying. Only one ' +
      'arrival sensor is ever on at a time, so the OR needs no extra gating.',
    'Y4 is a plain contact-to-coil rung: no(X18) out(Y4).',
  ],
  devices: [
    { address: 'X0', label: 'At Infeed', io: 'input', widget: 'sensor' },
    { address: 'X1', label: 'At Pad 1', io: 'input', widget: 'sensor' },
    { address: 'X2', label: 'At Pad 2', io: 'input', widget: 'sensor' },
    { address: 'X3', label: 'At Pad 3', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'At Pad 4', io: 'input', widget: 'sensor' },
    { address: 'X10', label: 'Reach Down', io: 'input', widget: 'sensor' },
    { address: 'X11', label: 'Reach Up', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Gripped', io: 'input', widget: 'sensor' },
    { address: 'X14', label: 'Pad 1 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Pad 2 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X16', label: 'Pad 3 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X17', label: 'Pad 4 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X18', label: 'Tray Full', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: 'Swing to Tray', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: 'Swing to Infeed', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y2', label: 'Reach Down', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y3', label: 'Gripper Close', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y4', label: 'Tray Full Lamp', io: 'output', widget: 'lamp', color: '#22c55e' },
  ],
  registers: [
    { address: 'M0', label: 'Carrying', note: 'set on rise(X12), reset on M1' },
    { address: 'M1', label: 'Placed pulse', note: 'one scan per placement, any pad' },
  ],
  allowedInstructions: ['contact-no', 'contact-nc', 'contact-rising', 'coil-out', 'coil-set', 'coil-reset'],
  maxRungs: 14,
  processId: 'pickPlace',
  scenarios: [
    {
      name: 'Four transfers fill the tray, then the arm parks',
      steps: [
        {
          label: 'First part placed on pad 1',
          holdMs: 4500,
          expectMachine: { placed: 1, jam: false },
          expect: { X14: true },
        },
        {
          label: 'Second part placed on pad 2, sailing past pad 1',
          holdMs: 6000,
          expectMachine: { placed: 2, jam: false },
          expect: { X15: true },
        },
        {
          label: 'Third part placed on pad 3',
          holdMs: 7500,
          expectMachine: { placed: 3, jam: false },
          expect: { X16: true },
        },
        {
          label: 'Fourth part placed on pad 4: the tray-full lamp lights',
          holdMs: 9000,
          expectMachine: { placed: 4, jam: false },
          expect: { X17: true, X18: true, Y4: true },
        },
        {
          label: 'Tray stays full: the arm parks instead of attempting a fifth pick',
          holdMs: 5000,
          expectMachine: { placed: 4, jam: false },
          expect: { Y2: false, Y3: false, X0: true, Y4: true },
        },
      ],
    },
  ],
};
