import type { PuzzleSpec } from '../types.js';

export const pickPlaceSupply: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pick-place-supply',
  title: 'Pick & Place: Wait for Supply',
  difficulty: 'hard',
  order: 27,
  category: 'pick-place',
  summary: 'The infeed runs dry between parts. Grip only what the conveyor has delivered.',
  briefing: [
    'The infeed is now on live production. The conveyor delivers one part at a',
    'time, and the pad reports Part at Infeed (X13). Every pick empties the pad,',
    'and it stays empty until the conveyor lands the next part.',
    '',
    'Operating procedure:',
    '',
    '  1. Run the four-pad tray cycle from the previous work order unchanged.',
    '  2. Before lowering or closing the gripper at the infeed, confirm X13 is on.',
    '     Closing the gripper over an empty pad grabs nothing and stalls the cycle',
    '     with the arm stuck at the bottom.',
    '  3. While the arm is at the infeed with no part ready (X13 off), light the',
    '     WAITING FOR SUPPLY lamp (Y6).',
    '  4. Fill all four pads, light the TRAY FULL lamp (Y4) from X18, and park the',
    '     arm retracted at the infeed.',
  ].join('\n'),
  hints: [
    'Add a no(X13) contact in series with the infeed branches of the reach-down ' +
      'and gripper-close rungs. Nothing else in the cycle changes.',
    'Y6 is a two-contact rung: no(X0) and nc(X13) out to Y6.',
  ],
  devices: [
    { address: 'X0', label: 'At Infeed', io: 'input', widget: 'sensor' },
    { address: 'X1', label: 'At Pad 1', io: 'input', widget: 'sensor' },
    { address: 'X2', label: 'At Pad 2', io: 'input', widget: 'sensor' },
    { address: 'X3', label: 'At Pad 3', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'At Pad 4', io: 'input', widget: 'sensor' },
    { address: 'X10', label: 'Reach Down', io: 'input', widget: 'sensor' },
    { address: 'X11', label: 'Reach Up', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Gripped', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'Part at Infeed', io: 'input', widget: 'sensor' },
    { address: 'X14', label: 'Pad 1 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Pad 2 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X16', label: 'Pad 3 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X17', label: 'Pad 4 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X18', label: 'Tray Full', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: 'Swing to Tray', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: 'Swing to Infeed', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y2', label: 'Reach Down', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y3', label: 'Gripper Close', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y4', label: 'Tray Full Lamp', io: 'output', widget: 'lamp', color: '#22c55e' },
    { address: 'Y6', label: 'Waiting for Supply', io: 'output', widget: 'lamp', color: '#fb7185' },
  ],
  registers: [
    { address: 'M0', label: 'Carrying', note: 'set on rise(X12), reset on M1' },
    { address: 'M1', label: 'Placed pulse', note: 'one scan per placement, any pad' },
  ],
  allowedInstructions: ['contact-no', 'contact-nc', 'contact-rising', 'coil-out', 'coil-set', 'coil-reset'],
  maxRungs: 15,
  processId: 'pickPlace',
  scenarios: [
    {
      name: 'Waits for supply, then fills the tray',
      steps: [
        {
          label: 'A part is ready at power-up, so the supply lamp stays dark',
          holdMs: 200,
          expect: { X13: true, Y6: false },
        },
        {
          label: 'First pick proceeds and lands on pad 1',
          holdMs: 4300,
          expectMachine: { placed: 1, jam: false },
          expect: { X14: true },
        },
        {
          label: 'Three more deliveries fill the tray despite the refill gaps',
          holdMs: 22000,
          expectMachine: { placed: 4, jam: false },
          expect: { X17: true, X18: true, Y4: true },
        },
        {
          label: 'Parked at a stocked infeed: the supply lamp is off',
          holdMs: 3000,
          expectMachine: { placed: 4, jam: false },
          expect: { X0: true, X13: true, Y6: false },
        },
      ],
    },
  ],
};
