import type { PuzzleSpec } from '../types.js';

export const pickPlaceSupply: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pick-place-supply',
  title: 'Pick & Place: Wait on Supply',
  difficulty: 'hard',
  order: 27,
  category: 'pick-place',
  summary: 'The infeed is no longer bottomless — wait for confirmed supply before gripping.',
  briefing: [
    'The infeed now reports whether a part has actually arrived (X13, Infeed Ready) —',
    'it depletes every time a part is picked and takes a moment to refill. Gripping',
    'at the infeed without checking X13 closes on empty air.',
    '',
    'Keep the 4-slot cycle from the last puzzle, but gate the reach-down and grip-',
    'close at the infeed on X13 as well. Light a SUPPLY WAIT lamp (Y6) whenever the',
    'arm is parked at the infeed with no part ready.',
  ].join('\n'),
  hints: [
    'Add X13 as one more AND condition on the infeed branches of the reach-down and',
    'grip-close rungs from the last puzzle — everything else is unchanged.',
    'Y6: X0 AND NOT X13 — lit only while parked at the infeed with nothing to grip.',
  ],
  devices: [
    { address: 'X0', label: 'At Infeed', io: 'input', widget: 'sensor' },
    { address: 'X1', label: 'At Slot 1', io: 'input', widget: 'sensor' },
    { address: 'X2', label: 'At Slot 2', io: 'input', widget: 'sensor' },
    { address: 'X3', label: 'At Slot 3', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'At Slot 4', io: 'input', widget: 'sensor' },
    { address: 'X10', label: 'Reach Down', io: 'input', widget: 'sensor' },
    { address: 'X11', label: 'Reach Up', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Gripped', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'Infeed Ready', io: 'input', widget: 'sensor' },
    { address: 'X14', label: 'Slot 1 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Slot 2 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X16', label: 'Slot 3 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X17', label: 'Slot 4 Occupied', io: 'input', widget: 'sensor' },
    { address: 'Y0', label: 'Swing to Tray', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: 'Swing to Infeed', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y2', label: 'Reach Down', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y3', label: 'Gripper Close', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y4', label: 'Tray Full', io: 'output', widget: 'lamp', color: '#22c55e' },
    { address: 'Y6', label: 'Supply Wait', io: 'output', widget: 'lamp', color: '#fb7185' },
  ],
  registers: [
    { address: 'M0', label: 'Carrying', note: 'set on rise(X12), reset on any placement pulse' },
    { address: 'C0', label: 'Placed count', note: 'preset K4 — counts placements, drives Y4' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'contact-rising',
    'coil-out',
    'coil-set',
    'coil-reset',
    'counter',
  ],
  maxRungs: 17,
  processId: 'pickPlace',
  scenarios: [
    {
      name: 'Waits for supply, then fills the tray',
      steps: [
        {
          label: 'A part is ready at power-up, so the first pick proceeds normally',
          holdMs: 4500,
          expectMachine: { placed: 1, jam: false },
          expect: { X14: true },
        },
        {
          label: 'Three more cycles fill the tray',
          holdMs: 22000,
          expectMachine: { placed: 4, jam: false },
          expect: { X17: true, Y4: true },
        },
      ],
    },
  ],
};
