import type { PuzzleSpec } from '../types.js';

export const pickPlaceFull: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pick-place-full',
  title: 'Pick & Place: Full Cycle',
  difficulty: 'hard',
  order: 28,
  category: 'pick-place',
  summary: 'Capstone: fill the tray, latch it full, and require a manual reset to run again.',
  briefing: [
    'Everything from the last puzzle stays the same, plus one more control: a RESET',
    'button (X20). Pressing it unloads the tray — clearing all four occupied lamps',
    'and the placed count — so the arm can run a fresh cycle. Wire X20 straight',
    'through to the RESET TRAY output (Y5), and reset your own placement counter',
    '(C0) alongside it so the TRAY FULL lamp clears too.',
  ].join('\n'),
  hints: [
    'Y5 is a direct passthrough of X20 — the machine itself only clears occupancy',
    'while nothing is being carried, so you do not need to guard it yourself.',
    'RST C0 on X20 as well, so Y4 (Tray Full) drops and a fresh cycle can begin.',
  ],
  devices: [
    { address: 'X0', label: 'At Infeed', io: 'input', widget: 'sensor' },
    { address: 'X1', label: 'At Slot 1', io: 'input', widget: 'sensor' },
    { address: 'X2', label: 'At Slot 2', io: 'input', widget: 'sensor' },
    { address: 'X3', label: 'At Slot 3', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'At Slot 4', io: 'input', widget: 'sensor' },
    { address: 'X10', label: 'Reach Down', io: 'input', widget: 'sensor' },
    { address: 'X11', label: 'Reach Up', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Gripped', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'Infeed Ready', io: 'input', widget: 'sensor' },
    { address: 'X14', label: 'Slot 1 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Slot 2 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X16', label: 'Slot 3 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X17', label: 'Slot 4 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X20', label: 'Reset', io: 'input', widget: 'momentary' },
    { address: 'Y0', label: 'Swing to Tray', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: 'Swing to Infeed', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y2', label: 'Reach Down', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y3', label: 'Gripper Close', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y4', label: 'Tray Full', io: 'output', widget: 'lamp', color: '#22c55e' },
    { address: 'Y5', label: 'Reset Tray', io: 'output', widget: 'motor', color: '#fb7185' },
    { address: 'Y6', label: 'Supply Wait', io: 'output', widget: 'lamp', color: '#fb7185' },
  ],
  registers: [
    { address: 'M0', label: 'Carrying', note: 'set on rise(X12), reset on any placement pulse' },
    { address: 'C0', label: 'Placed count', note: 'preset K4 — counts placements, drives Y4; reset by X20' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'contact-rising',
    'coil-out',
    'coil-set',
    'coil-reset',
    'counter',
  ],
  maxRungs: 18,
  processId: 'pickPlace',
  scenarios: [
    {
      name: 'Fill the tray, reset it, and run a fresh cycle',
      steps: [
        {
          label: 'All four cycles fill the tray',
          holdMs: 27000,
          expectMachine: { placed: 4, jam: false },
          expect: { X17: true, Y4: true },
        },
        {
          label: 'Press Reset — the tray unloads',
          setInputs: { X20: true },
          holdMs: 150,
          expectMachine: { slot1: false, slot2: false, slot3: false, slot4: false, placed: 0 },
          expect: { Y4: false },
        },
        {
          label: 'Release Reset — a fresh cycle places a part in slot 1 again',
          setInputs: { X20: false },
          holdMs: 4500,
          expectMachine: { placed: 1, jam: false },
          expect: { X14: true },
        },
      ],
    },
  ],
};
