import type { PuzzleSpec } from '../types.js';

export const pickPlaceFull: PuzzleSpec = {
  kind: 'ladder',
  slug: 'pick-place-full',
  title: 'Pick & Place: Production Run',
  difficulty: 'hard',
  order: 28,
  category: 'pick-place',
  summary: 'Run a two-tray production order with operator unloads, then shut down clean.',
  briefing: [
    'Final acceptance test: complete a production order of TWO full trays.',
    '',
    'Operating procedure:',
    '',
    '  1. Fill the tray using the complete cycle from the previous work orders:',
    '     supply gating on X13, first-free-pad delivery, Y4 lamp from X18.',
    '  2. When the tray is full, the operator lifts the finished parts off and',
    '     holds the UNLOAD button (X20). Pass X20 through to the Unload Tray',
    '     output (Y5): while Y5 is on, the machine clears all four occupancy',
    '     sensors.',
    '  3. Count completed trays on counter C0, preset K2. Each rise of Tray Full',
    '     (X18) is one finished tray.',
    '  4. When C0 completes, light ORDER COMPLETE (Y7). The order is closed: even',
    '     after the operator unloads the second tray, do not start another pick.',
    '     Park the arm retracted at the infeed and leave Y7 on.',
    '',
    'Safety notes:',
    '',
    '  1. The machine ignores Y5 while a part is being carried, so a direct',
    '     X20-to-Y5 rung is safe.',
    '  2. All earlier rules still apply: no release over an occupied pad, no',
    '     mid-air release, no pick from an empty infeed.',
  ].join('\n'),
  hints: [
    'Three new one-line rungs: no(X20) out(Y5), no(X18) driving counter C0 with ' +
      'preset K2, and no(C0) out(Y7).',
    'Close the order by adding nc(C0) in series with the infeed branches of the ' +
      'reach-down and gripper-close rungs, next to nc(X18) and no(X13). Once C0 ' +
      'completes, picks stay blocked even after the tray is cleared.',
    'Do not reset C0 anywhere. Holding its done state is exactly what keeps the ' +
      'order closed.',
  ],
  devices: [
    { address: 'X0', label: 'At Infeed', io: 'input', widget: 'sensor' },
    { address: 'X1', label: 'At Pad 1', io: 'input', widget: 'sensor' },
    { address: 'X2', label: 'At Pad 2', io: 'input', widget: 'sensor' },
    { address: 'X3', label: 'At Pad 3', io: 'input', widget: 'sensor' },
    { address: 'X4', label: 'At Pad 4', io: 'input', widget: 'sensor' },
    { address: 'X10', label: 'Reach Down', io: 'input', widget: 'sensor' },
    { address: 'X11', label: 'Reach Up', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Gripped', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'Part at Infeed', io: 'input', widget: 'sensor' },
    { address: 'X14', label: 'Pad 1 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Pad 2 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X16', label: 'Pad 3 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X17', label: 'Pad 4 Occupied', io: 'input', widget: 'sensor' },
    { address: 'X18', label: 'Tray Full', io: 'input', widget: 'sensor' },
    { address: 'X20', label: 'Unload Button', io: 'input', widget: 'momentary' },
    { address: 'Y0', label: 'Swing to Tray', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y1', label: 'Swing to Infeed', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y2', label: 'Reach Down', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y3', label: 'Gripper Close', io: 'output', widget: 'motor', color: '#f59e0b' },
    { address: 'Y4', label: 'Tray Full Lamp', io: 'output', widget: 'lamp', color: '#22c55e' },
    { address: 'Y5', label: 'Unload Tray', io: 'output', widget: 'motor', color: '#fb7185' },
    { address: 'Y6', label: 'Waiting for Supply', io: 'output', widget: 'lamp', color: '#fb7185' },
    { address: 'Y7', label: 'Order Complete', io: 'output', widget: 'lamp', color: '#facc15' },
  ],
  registers: [
    { address: 'M0', label: 'Carrying', note: 'set on rise(X12), reset on M1' },
    { address: 'M1', label: 'Placed pulse', note: 'one scan per placement, any pad' },
    { address: 'C0', label: 'Tray counter', note: 'preset K2, counts rises of X18, never reset' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'contact-rising',
    'coil-out',
    'coil-set',
    'coil-reset',
    'counter',
  ],
  maxRungs: 18,
  processId: 'pickPlace',
  scenarios: [
    {
      name: 'Two trays complete the order',
      steps: [
        {
          label: 'First tray fills and the tray-full lamp lights',
          holdMs: 27000,
          expectMachine: { placed: 4, jam: false },
          expect: { X18: true, Y4: true, Y7: false },
        },
        {
          label: 'Operator unloads the first tray',
          setInputs: { X20: true },
          holdMs: 150,
          expectMachine: { slot1: false, slot2: false, slot3: false, slot4: false, placed: 0 },
          expect: { Y4: false, Y7: false },
        },
        {
          label: 'Second tray fills and the order completes',
          setInputs: { X20: false },
          holdMs: 27000,
          expectMachine: { placed: 4, jam: false },
          expect: { X18: true, Y4: true, Y7: true },
        },
        {
          label: 'Operator unloads the finished order',
          setInputs: { X20: true },
          holdMs: 150,
          expectMachine: { placed: 0 },
          expect: { Y4: false, Y7: true },
        },
        {
          label: 'Order closed: the arm parks instead of starting a third tray',
          setInputs: { X20: false },
          holdMs: 8000,
          expectMachine: { placed: 0, jam: false },
          expect: { X0: true, Y2: false, Y3: false, Y7: true },
        },
      ],
    },
  ],
};
