import type { PuzzleSpec } from '../types.js';
import { FLOW_RANGE, LEVEL_RANGE, VALVE_RANGE } from './32-tank-level-readout.js';

export const tankPid: PuzzleSpec = {
  kind: 'ladder',
  slug: 'tank-pid',
  title: 'Vessel: PID',
  difficulty: 'hard',
  order: 35,
  category: 'process-control',
  summary: 'Swap the hand-built regulator for a PID block and close the offset for good.',
  briefing: [
    'Your proportional regulator works, and it always sits a little away from setpoint,',
    'and how far away depends on the load. Adding a bias by hand fixes that at one load',
    'and one load only. What is actually needed is something that watches the error not',
    'go away and keeps pushing until it does, which is integral action, and the PLC has',
    'a block for it.',
    '',
    '## Equipment',
    '- D0 LEVEL, D20 VALVE, D1 DISCHARGE FLOW: as before.',
    '- D30 SETPOINT: 60 % (2400 counts) in every scenario here.',
    '- X0 AUTO and X3 DISCHARGE DEMAND: as before.',
    '- Y0 DISCHARGE PUMP, Y1 ON SETPOINT: the pump, and a lamp saying the level is',
    '  within 2 % of setpoint.',
    '',
    '## Sequence of operation',
    '1. With AUTO off, hold the valve shut, the pump stopped and the lamp out.',
    '2. With AUTO on, run the pump on demand and hand the valve to a PID block: setpoint',
    '   D30, measurement D0, output D20.',
    '3. Tune it so the level reaches setpoint and stays there through a load change,',
    '   without slamming past it on the way.',
    '4. Light ON SETPOINT (Y1) while the level is within 80 counts of setpoint.',
    '',
    '## Field notes',
    '- The block takes its gain in hundredths, so 250 is a gain of 2.50. It works in a',
    '  wider accumulator than a D register, which is exactly why it can carry a',
    '  fractional gain when your hand-built version could not.',
    '- Integral time is in milliseconds, and smaller means more aggressive. Zero turns',
    '  the term off and leaves you with the P controller you already had.',
    '- Set the output range to the valve: 0 to 4000. The block will not command past it,',
    '  and it stops accumulating while it is against a limit, which is what keeps a long',
    '  fill from arriving with a wound-up integral and sailing straight past setpoint.',
    '- Start around gain 300, integral 4000 ms. Then make it better.',
    '',
    '## Acceptance',
    '- Starting from a quarter full, the level reaches setpoint and holds within 1 %,',
    '  having overshot by no more than 5 %.',
    '- A load change is absorbed and the level comes back to within 1 %, where a',
    '  proportional-only regulator would have left an offset.',
  ].join('\n'),
  hints: [
    'One rung holds the loop: X0 (NO) into a PID block. Its destination is D20, ' +
      'its setpoint operand is D30 and its measurement operand is D0.',
    'The valve still needs shutting when the loop is not running, so keep the ' +
      'X0 (NC) into MOV K0 D20 rung. The PID block clears its own internal state ' +
      'while its rung is off, so it will not come back wound up.',
    'Setpoint has to get into D30 before the loop reads it: an unconditional MOV ' +
      'K2400 D30 rung, placed above the loop so the same scan sees it.',
    'The lamp is two compare contacts in series on Y1: D0 >= K2320 and ' +
      'D0 <= K2480. Gate it on X0 so it is dark when the loop is not running.',
    'Too much overshoot on the first fill means the integral is too fast for how ' +
      'long the valve spends wide open. Lengthen the integral time before you ' +
      'reach for the gain.',
  ],
  devices: [
    { address: 'X0', label: 'Auto', io: 'input', widget: 'toggle' },
    { address: 'X3', label: 'Discharge Demand', io: 'input', widget: 'toggle' },
    {
      address: 'D0',
      label: 'Level',
      io: 'input',
      widget: 'trend',
      signal: 'analog',
      range: LEVEL_RANGE,
      color: '#38bdf8',
    },
    {
      address: 'D1',
      label: 'Discharge Flow',
      io: 'input',
      widget: 'bar',
      signal: 'analog',
      range: FLOW_RANGE,
      color: '#c084fc',
    },
    {
      address: 'D20',
      label: 'Supply Valve',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: VALVE_RANGE,
      color: '#34d399',
    },
    { address: 'Y0', label: 'Discharge Pump', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y1', label: 'On Setpoint', io: 'output', widget: 'lamp', color: '#4ade80' },
  ],
  registers: [{ address: 'D30', label: 'Setpoint', note: 'raw counts; K2400 is 60 %' }],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'compare',
    'mov',
    'math',
    'pid',
    'coil-out',
    'coil-set',
    'coil-reset',
  ],
  maxRungs: 10,
  processId: 'tank',
  scenarios: [
    {
      name: 'Reaches setpoint without sailing past it',
      steps: [
        {
          label: 'Switch to Auto from a quarter full',
          setInputs: { X0: true, X3: false },
          holdMs: 500,
          expect: { Y1: false },
        },
        {
          label: 'The loop fills to setpoint and settles there',
          holdMs: 40000,
          control: {
            device: 'D0',
            setpoint: 2400,
            band: 40,
            settleMs: 10000,
            maxOvershoot: 200,
            maxSteadyError: 40,
          },
          expect: { Y1: true },
          expectMachine: { jam: false, overflow: false },
        },
      ],
      // Mostly the unavoidable transit from a quarter full up to setpoint.
      parIae: 2900,
    },
    {
      name: 'Absorbs a load change with no lasting offset',
      steps: [
        {
          label: 'Settle on setpoint',
          setInputs: { X0: true, X3: false },
          holdMs: 40000,
          until: { analog: { D0: { min: 2360, max: 2440 } } },
          thenHoldMs: 8000,
          expect: { Y1: true },
        },
        {
          label: 'Demand starts: the loop takes the hit and comes all the way back',
          setInputs: { X3: true },
          holdMs: 30000,
          expect: { Y0: true, Y1: true },
          control: {
            device: 'D0',
            setpoint: 2400,
            band: 40,
            settleMs: 8000,
            maxSteadyError: 40,
          },
          expectMachine: { jam: false },
        },
        {
          label: 'Demand stops: it comes back from the other side too',
          setInputs: { X3: false },
          holdMs: 30000,
          expect: { Y0: false, Y1: true },
          control: {
            device: 'D0',
            setpoint: 2400,
            band: 40,
            settleMs: 8000,
            maxSteadyError: 40,
          },
          expectMachine: { jam: false, overflow: false },
        },
      ],
      parIae: 2900,
    },
    {
      name: 'Auto off shuts the valve',
      steps: [
        {
          label: 'Run up to setpoint',
          setInputs: { X0: true, X3: false },
          holdMs: 40000,
          until: { analog: { D0: { min: 2360, max: 2440 } } },
          expect: { Y1: true },
        },
        {
          label: 'Out of Auto: valve shut, pump stopped, lamp out',
          setInputs: { X0: false },
          holdMs: 1000,
          expect: { Y0: false, Y1: false },
          expectAnalog: { D20: { max: 0 } },
        },
        {
          label: 'Back into Auto: the loop picks up again without a wound-up kick',
          setInputs: { X0: true },
          holdMs: 20000,
          control: {
            device: 'D0',
            setpoint: 2400,
            band: 60,
            settleMs: 6000,
            maxOvershoot: 200,
          },
          expectMachine: { jam: false, overflow: false },
        },
      ],
    },
  ],
};
