import type { PuzzleSpec } from '../types.js';
import { FLOW_RANGE, LEVEL_RANGE, VALVE_RANGE } from './32-tank-level-readout.js';

export const tankAuto: PuzzleSpec = {
  kind: 'ladder',
  slug: 'tank-auto',
  title: 'Vessel: Automatic Operation',
  difficulty: 'hard',
  order: 36,
  category: 'process-control',
  summary:
    'Capstone: two recipe setpoints, a tracked loop, alarms, and a high-level trip that latches.',
  briefing: [
    'Handing the vessel over to production. Two products run on it at different working',
    'levels, the operator picks between them with a selector, and the loop has to move',
    'the vessel from one to the other without putting it on the floor or over the top.',
    'On top of that it needs the protection any real vessel has: a high-level trip that',
    'shuts the supply and stays shut until somebody acknowledges it.',
    '',
    '## Equipment',
    '- D0 LEVEL, D1 DISCHARGE FLOW, D20 VALVE: as before.',
    '- X0 AUTO, X3 DISCHARGE DEMAND: as before.',
    '- X4 RECIPE B: maintained selector. Off is recipe A at 40 % (1600 counts), on is',
    '  recipe B at 70 % (2800 counts).',
    '- X5 ALARM RESET: momentary push button.',
    '- X6 MANUAL FILL: maintained selector. Hand mode. It takes the valve off the loop',
    '  and holds it wide open, which is exactly how vessels get overfilled in real life.',
    '- X2 HIGH LEVEL: the independent high float, hard wired at 90 %. It is a separate',
    '  device from the transmitter on purpose, because a trip that trusts the same',
    '  instrument it is protecting against is not a trip.',
    '- Y0 DISCHARGE PUMP, Y1 ON SETPOINT, Y2 HIGH LEVEL TRIP.',
    '- D30 SETPOINT, M0 TRIP LATCH (see Working Registers).',
    '',
    '## Sequence of operation',
    '1. Load the setpoint from the recipe selector into D30 every scan: 1600 for A,',
    '   2800 for B.',
    '2. With AUTO on and no trip standing, run the PID loop from D30 onto the valve.',
    '3. With MANUAL FILL on and no trip standing, ignore the loop and hold the valve',
    '   wide open instead.',
    '4. With neither selector on, hold the valve shut.',
    '5. Run the discharge pump whenever AUTO is on and demand asks for it.',
    '6. Light ON SETPOINT (Y1) while the level is within 80 counts of D30.',
    '7. If the high float X2 makes, latch the trip: shut the valve, light Y2, and hold',
    '   it all latched even after the level falls back.',
    '8. ALARM RESET (X5) clears the latch, and only then may the valve be driven again.',
    '',
    '## Interlocks and safety',
    '- The trip wins over everything. A latched trip means a shut valve whatever the PID',
    '  block is asking for and whatever mode the operator has selected.',
    '- Reset must not restart anything on its own beyond releasing the latch.',
    '- The vessel must never overflow and the pump must never run dry, in any scenario.',
    '',
    '## Field notes',
    '- Changing recipe is a step change in setpoint, which is the harshest thing you can',
    '  ask a tuned loop to do. Coming down is slower than going up here, because the only',
    '  way down is the drain.',
    '- The order of your rungs matters more than usual: whatever writes the valve last in',
    '  a scan is what the valve gets.',
    '',
    '## Acceptance',
    '- Both recipes are held within 1 %, and the change between them settles.',
    '- The trip latches on the float, survives the level falling back, and clears only',
    '  on reset.',
  ].join('\n'),
  hints: [
    'Setpoint selection is the MOV-selection idiom again: X4 (NO) into MOV K2800 ' +
      'D30, X4 (NC) into MOV K1600 D30. Put it above the loop so the same scan ' +
      'uses the new value.',
    'The trip latch is a seal-in on M0: (X2 OR M0) AND NOT X5, driven into M0. ' +
      'Y2 is then a plain coil on M0.',
    'Give the loop rung an M0 (NC) contact in series with X0 (NO), so a standing ' +
      'trip both stops the block and clears its internal state.',
    'Everything that writes the valve is really one ordered list, top to bottom: ' +
      'the PID block first, then MOV K4000 D20 for hand mode, then MOV K0 D20 ' +
      'last. The last rung that conducts is the one the valve obeys, which is ' +
      'what makes the trip beat both modes.',
    'That shut rung conducts on M0 (NO), or on neither selector being on: two ' +
      'rows joined by a vertical link, the lower one being X0 (NC) in series ' +
      'with X6 (NC).',
    'The on-setpoint band moves with the recipe, so it cannot be two constants. ' +
      'Work out D30 minus K80 and D30 plus K80 into two spare registers, then ' +
      'compare D0 against those.',
  ],
  devices: [
    { address: 'X0', label: 'Auto', io: 'input', widget: 'toggle' },
    { address: 'X2', label: 'High Level Float', io: 'input', widget: 'sensor' },
    { address: 'X3', label: 'Discharge Demand', io: 'input', widget: 'toggle' },
    { address: 'X4', label: 'Recipe B', io: 'input', widget: 'selector' },
    { address: 'X5', label: 'Alarm Reset', io: 'input', widget: 'momentary' },
    { address: 'X6', label: 'Manual Fill', io: 'input', widget: 'toggle' },
    {
      address: 'D0',
      label: 'Level',
      io: 'input',
      widget: 'trend',
      signal: 'analog',
      range: LEVEL_RANGE,
      color: '#38bdf8',
    },
    {
      address: 'D1',
      label: 'Discharge Flow',
      io: 'input',
      widget: 'bar',
      signal: 'analog',
      range: FLOW_RANGE,
      color: '#c084fc',
    },
    {
      address: 'D20',
      label: 'Supply Valve',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: VALVE_RANGE,
      color: '#34d399',
    },
    { address: 'Y0', label: 'Discharge Pump', io: 'output', widget: 'motor', color: '#a78bfa' },
    { address: 'Y1', label: 'On Setpoint', io: 'output', widget: 'lamp', color: '#4ade80' },
    { address: 'Y2', label: 'High Level Trip', io: 'output', widget: 'lamp', color: '#f87171' },
  ],
  registers: [
    { address: 'D30', label: 'Active setpoint', note: 'K1600 for recipe A, K2800 for recipe B' },
    { address: 'D33', label: 'Band low', note: 'setpoint minus 80 counts' },
    { address: 'D34', label: 'Band high', note: 'setpoint plus 80 counts' },
    { address: 'M0', label: 'Trip latch', note: 'set by the high float, cleared by reset only' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'contact-rising',
    'compare',
    'mov',
    'math',
    'pid',
    'coil-out',
    'coil-set',
    'coil-reset',
  ],
  maxRungs: 12,
  processId: 'tank',
  scenarios: [
    {
      name: 'Recipe A, then a change up to recipe B',
      steps: [
        {
          label: 'Auto on, recipe A: settle at 40 %',
          setInputs: { X0: true, X3: false, X4: false },
          holdMs: 40000,
          control: {
            device: 'D0',
            setpoint: 1600,
            band: 40,
            settleMs: 8000,
            maxOvershoot: 250,
            maxSteadyError: 40,
          },
          expect: { Y1: true, Y2: false },
          expectMachine: { jam: false },
        },
        {
          label: 'Change to recipe B: the loop steps the vessel up to 70 %',
          setInputs: { X4: true },
          holdMs: 40000,
          control: {
            device: 'D0',
            setpoint: 2800,
            band: 40,
            settleMs: 8000,
            maxOvershoot: 250,
            maxSteadyError: 40,
          },
          expect: { Y1: true, Y2: false },
          expectMachine: { jam: false, overflow: false },
        },
        {
          label: 'Back to recipe A with demand running: the vessel comes down and holds',
          setInputs: { X4: false, X3: true },
          holdMs: 50000,
          expect: { Y0: true, Y1: true },
          control: {
            device: 'D0',
            setpoint: 1600,
            band: 60,
            settleMs: 8000,
            maxSteadyError: 60,
          },
          expectMachine: { jam: false, dryRun: false },
        },
      ],
      // Three setpoint moves in one scenario, so most of this is transit the
      // vessel cannot avoid. Tuning buys the rest.
      parIae: 6300,
    },
    {
      // The float is a real device on a real vessel, so the only way to make it
      // is to actually overfill: hand mode holds the valve open past 90 % and
      // the trip has to take it away again.
      name: 'Hand mode overfills, and the trip takes the valve away',
      steps: [
        {
          label: 'Auto on, recipe B: settle at 70 %',
          setInputs: { X0: true, X3: false, X4: true },
          holdMs: 40000,
          until: { analog: { D0: { min: 2760, max: 2840 } } },
          thenHoldMs: 4000,
          expect: { Y1: true, Y2: false },
        },
        {
          label: 'Hand mode: the valve goes wide open and the vessel climbs past setpoint',
          setInputs: { X6: true },
          holdMs: 2000,
          expectAnalog: { D20: { min: 4000 } },
          expect: { Y2: false },
        },
        {
          label: 'The float makes at 90 %: the trip latches and the valve shuts',
          holdMs: 12000,
          until: { bits: { X2: true } },
          thenHoldMs: 300,
          expect: { Y2: true },
          expectAnalog: { D20: { max: 0 } },
          expectMachine: { jam: false, overflow: false },
        },
        {
          label: 'The level falls back below the float, and the trip stays latched',
          holdMs: 8000,
          expect: { Y2: true, X2: false },
          expectAnalog: { D20: { max: 0 } },
          expectMachine: { jam: false },
        },
        {
          label: 'Reset while still in hand mode clears the latch and the valve opens again',
          setInputs: { X5: true },
          holdMs: 600,
          expect: { Y2: false },
          expectAnalog: { D20: { min: 4000 } },
        },
        {
          label: 'Back to Auto: the loop pulls the vessel down to setpoint and holds it',
          setInputs: { X5: false, X6: false },
          holdMs: 40000,
          control: {
            device: 'D0',
            setpoint: 2800,
            band: 60,
            settleMs: 8000,
          },
          expect: { Y1: true, Y2: false },
          expectMachine: { jam: false, overflow: false },
        },
      ],
    },
    {
      name: 'Both selectors off parks the vessel',
      steps: [
        {
          label: 'Run up on recipe A',
          setInputs: { X0: true, X3: false, X4: false },
          holdMs: 40000,
          until: { analog: { D0: { min: 1560, max: 1640 } } },
          expect: { Y1: true },
        },
        {
          label: 'Out of Auto: valve shut, pump stopped, lamps out',
          setInputs: { X0: false, X3: true },
          holdMs: 1000,
          expect: { Y0: false, Y1: false, Y2: false },
          expectAnalog: { D20: { max: 0 } },
        },
        {
          label: 'Nothing moves while both selectors are off',
          holdMs: 10000,
          expect: { Y0: false },
          expectAnalog: { D20: { max: 0 } },
          expectMachine: { jam: false },
        },
      ],
    },
  ],
};
