import type { PuzzleSpec } from '../types.js';
import { POSITION_RANGE, RAMP_RANGE, REFERENCE_RANGE, SPEED_RANGE } from './37-axis-jog.js';

export const axisProfile: PuzzleSpec = {
  kind: 'ladder',
  slug: 'axis-profile',
  title: 'Traverse: Rapid and Approach',
  difficulty: 'medium',
  order: 38,
  category: 'motion',
  summary: 'Position a carriage with a speed reference by slowing down before the target, not at it.',
  briefing: [
    'The carriage now has to stop somewhere, not just run. There are two work stations',
    'on the rail: a pick station near the home end and a drop station near the far end.',
    'A selector says which one the carriage should be at, and the carriage is expected',
    'to be sitting inside that station window whenever it is not travelling.',
    '',
    'The drive still only takes a speed. Dropping the run coil on arrival does not',
    'arrive, it starts a ramp that carries you well past the mark. So the program has',
    'to see the target coming and change speed before it gets there.',
    '',
    '## Equipment',
    '- D0 POSITION: the transmitter. The pick station is at 400 counts, the drop station',
    '  at 3400, and a station window is 60 counts either side.',
    '- D20 SPEED REFERENCE, D40 ACCEL, D41 DECEL: as before. The drive still trips above',
    '  2000 on accel and 2500 on decel.',
    '- X0 SEND TO DROP: maintained selector. On means the drop station is the target,',
    '  off means the pick station is.',
    '- X12 AT PICK and X13 AT DROP: station proximity sensors, true inside the window.',
    '- X10 AT HOME and X11 AT END: the overtravel limits. They are not stations.',
    '- D30 TARGET and D31 DISTANCE TO GO: your working registers.',
    '',
    '## Sequence of operation',
    '1. Load K2000 into D40 and K2500 into D41.',
    '2. Put the selected target into D30: K3400 with the selector on, K400 with it off.',
    '3. Work out how far there is to go: target minus position, into D31. It is signed,',
    '   and the sign is the direction to travel in.',
    '4. Run forward while D31 is more than 40, reverse while it is less than minus 40.',
    '5. Use the full speed reference while there is a long way to go, and a slow',
    '   approach reference once the target is close.',
    '',
    '## Field notes',
    '- Stopping distance is the thing to work out, not the thing to guess. At full',
    '  reference this drive runs 500 counts a second, and 2500 counts a second of',
    '  deceleration takes it back to a crawl in well under two seconds. Give it about',
    '  400 counts of warning and the approach does the rest.',
    '- The last stretch wants a reference of about K400. Slow enough that the final',
    '  ramp is only a few counts, fast enough that the approach is not the whole cycle.',
    '- A distance to go is signed, so "close to the target" is two comparisons, not one.',
    '  Compare it against your slow-down distance and against the negative of it.',
    '',
    '## Acceptance',
    '- Selecting each station parks the carriage inside that station window and it',
    '  stays there.',
    '- Neither run coil is left on once the carriage has arrived.',
    '- Getting there promptly scores better than crawling the whole way.',
  ].join('\n'),
  hints: [
    'Two MOV rungs give you the target: X0 into MOV K3400 D30, and an NC contact on ' +
      'X0 into MOV K400 D30. Only one of them conducts at a time, so they never fight.',
    'The distance to go is one SUB: D30 minus D0 into D31, on a plain wire so it runs ' +
      'every scan.',
    'Direction is two compare contacts straight onto the run coils: D31 > K40 drives ' +
      'Y0 and D31 < K-40 drives Y1. The 40 is the deadband that stops the carriage ' +
      'hunting once it has arrived.',
    'For the speed reference, put the two "far away" compares (D31 > K400 and ' +
      'D31 < K-400) on parallel rows into MOV K4000 D20, and the two "close" compares ' +
      '(D31 <= K400 and D31 >= K-400) in series into MOV K400 D20.',
  ],
  devices: [
    { address: 'X0', label: 'Send To Drop', io: 'input', widget: 'selector' },
    { address: 'X10', label: 'At Home', io: 'input', widget: 'sensor' },
    { address: 'X11', label: 'At End', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'At Pick Station', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'At Drop Station', io: 'input', widget: 'sensor' },
    {
      address: 'D0',
      label: 'Position',
      io: 'input',
      widget: 'trend',
      signal: 'analog',
      range: POSITION_RANGE,
      color: '#38bdf8',
    },
    {
      address: 'D1',
      label: 'Speed',
      io: 'input',
      widget: 'gauge',
      signal: 'analog',
      range: SPEED_RANGE,
      color: '#fbbf24',
    },
    {
      address: 'D20',
      label: 'Speed Reference',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: REFERENCE_RANGE,
      color: '#34d399',
    },
    {
      address: 'D40',
      label: 'Accel Rate',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: RAMP_RANGE,
      color: '#a78bfa',
    },
    {
      address: 'D41',
      label: 'Decel Rate',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: RAMP_RANGE,
      color: '#a78bfa',
    },
    { address: 'Y0', label: 'Run Forward', io: 'output', widget: 'motor', color: '#34d399' },
    { address: 'Y1', label: 'Run Reverse', io: 'output', widget: 'motor', color: '#f97316' },
  ],
  registers: [
    { address: 'D30', label: 'Target position', note: 'raw counts; K400 or K3400' },
    { address: 'D31', label: 'Distance to go', note: 'target minus position, signed' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'compare',
    'mov',
    'math',
    'hwire',
    'coil-out',
  ],
  maxRungs: 12,
  processId: 'axis',
  scenarios: [
    {
      name: 'Out to the drop station and back',
      steps: [
        {
          label: 'Select the drop station',
          setInputs: { X0: true },
          holdMs: 30000,
          until: { bits: { X13: true } },
          expectMachine: { jam: false },
        },
        {
          label: 'It settles inside the window and shuts the drive off',
          holdMs: 3000,
          expect: { X13: true, Y0: false, Y1: false },
          expectAnalog: { D0: { min: 3340, max: 3460 }, D1: { min: 0, max: 0 } },
          expectMachine: { jam: false },
        },
        {
          label: 'Select the pick station again',
          setInputs: { X0: false },
          holdMs: 30000,
          until: { bits: { X12: true } },
          expectMachine: { jam: false },
        },
        {
          label: 'It settles inside that window too',
          holdMs: 3000,
          expect: { X12: true, Y0: false, Y1: false },
          expectAnalog: { D0: { min: 340, max: 460 }, D1: { min: 0, max: 0 } },
          expectMachine: { jam: false },
        },
      ],
      // Measured against the reference profile (400 counts of warning, K400 on
      // approach). Creeping the whole way still arrives, and still scores less.
      parMs: 21500,
    },
    {
      name: 'It holds the station it is told to hold',
      steps: [
        {
          label: 'Sit at the pick station with nothing asked of it',
          holdMs: 6000,
          expect: { X12: true, Y0: false, Y1: false },
          expectMachine: { jam: false },
        },
        {
          label: 'Send it to the drop station',
          setInputs: { X0: true },
          holdMs: 30000,
          until: { bits: { X13: true } },
          expectMachine: { jam: false },
        },
        {
          label: 'And it stays there, without drifting or hunting',
          holdMs: 8000,
          expect: { X13: true, Y0: false, Y1: false },
          expectAnalog: { D0: { min: 3340, max: 3460 } },
          expectMachine: { jam: false },
        },
      ],
    },
  ],
};
