import type { PuzzleSpec } from '../types.js';
import { POSITION_RANGE, RAMP_RANGE, REFERENCE_RANGE, SPEED_RANGE } from './37-axis-jog.js';

export const axisLoaded: PuzzleSpec = {
  kind: 'ladder',
  slug: 'axis-loaded',
  title: 'Traverse: Loaded and Empty',
  difficulty: 'hard',
  order: 39,
  category: 'motion',
  summary: 'One machine, two ramp tables: swap the drive parameters in flight as the load comes and goes.',
  briefing: [
    'The carriage has forks on it now, and it shuttles pallets from the pick station to',
    'the drop station. That changes the machine twice per cycle, because a loaded',
    'carriage and an empty one are not the same machine at all.',
    '',
    'The motor can only pull so hard, and the forks can only hold so hard. Both limits',
    'fall by half with a pallet on board. So the ramp parameters cannot be set once at',
    'power-up: they are part of the cycle, and they have to change when the load does.',
    '',
    '## Equipment',
    '- D0 POSITION, D20 SPEED REFERENCE, D40 ACCEL, D41 DECEL, Y0 and Y1: as before.',
    '- Y4 FORKS: closes while energised. The forks pick a pallet up when they finish',
    '  closing at the pick station and set it down when they finish opening at the drop',
    '  station. Both only work with the carriage stopped.',
    '- X14 LOAD ON FORKS: true while a pallet is actually on board. This is the signal',
    '  the whole exercise turns on.',
    '- X12 AT PICK, X13 AT DROP, X10 AT HOME, X11 AT END, D1 SPEED: as before.',
    '',
    '## Drive parameter tables',
    '- Empty: accel K2000, decel K2500. About 400 counts of stopping distance.',
    '- Loaded: accel K1000, decel K1200. About 1000 counts of stopping distance.',
    '',
    '## Sequence of operation',
    '1. Select the ramp table from X14, every scan, both parameters and the slow-down',
    '   distance you compare against.',
    '2. With no load, the target is the pick station. With a load, it is the drop',
    '   station. The carriage therefore shuttles on its own once the forks work.',
    '3. At the pick station, stopped and empty, close the forks and pick the pallet up.',
    '4. At the drop station, stopped and loaded, open the forks and set it down.',
    '5. Repeat. The scenarios run two full pallets.',
    '',
    '## Interlocks and safety',
    '- Accelerating a loaded carriage on the empty table trips the drive on overcurrent',
    '  before it has gone anywhere.',
    '- Braking a loaded carriage on the empty table slides the pallet off the forks.',
    '- Operating the forks while the carriage is still moving wrecks them. Wait for the',
    '  speed to actually be zero, not for the run coil to drop.',
    '- Setting a pallet down anywhere except the drop station drops it on the floor.',
    '- Past the drop station is rack structure, not more rail. An empty carriage can run',
    '  the whole length; a loaded one that overshoots hits the rack face.',
    '',
    '## Field notes',
    '- Half the ramp rate is twice the stopping distance, and the distance is what you',
    '  actually compare against. Swapping the two parameters and forgetting the third',
    '  number is the classic version of this mistake: the drive survives, and the pallet',
    '  sails straight through the station window.',
    '- You need a latch to remember that a pallet has been released, or the forks will',
    '  close again on the way home and the cycle will never restart properly.',
    '',
    '## Acceptance',
    '- Two pallets moved, nothing tripped, nothing dropped.',
    '- A tidy cycle scores better than a timid one.',
  ].join('\n'),
  hints: [
    'Six MOV rungs make the two tables: X14 into MOV K1000 D40, MOV K1200 D41 and ' +
      'MOV K1000 D32, then an NC contact on X14 into MOV K2000 D40, MOV K2500 D41 and ' +
      'MOV K400 D32. D32 is your slow-down distance.',
    'The target comes from the same bit: X14 into MOV K3400 D30, NC X14 into MOV ' +
      'K400 D30. Distance to go is SUB D30 D0 into D31, exactly as before.',
    'Comparing against a negative distance needs the negative to exist: SUB K0 D32 ' +
      'into D33 gives it to you, and then D31 < D33 is the reverse-side test.',
    'For the forks, latch M0 when you are at the drop station, stopped and still ' +
      'loaded, and reset it when you are back at the pick station, stopped and empty. ' +
      'Drive Y4 from an NC contact on M0 and the fork sequence takes care of itself.',
  ],
  devices: [
    { address: 'X10', label: 'At Home', io: 'input', widget: 'sensor' },
    { address: 'X11', label: 'At End', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'At Pick Station', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'At Drop Station', io: 'input', widget: 'sensor' },
    { address: 'X14', label: 'Load On Forks', io: 'input', widget: 'sensor' },
    {
      address: 'D0',
      label: 'Position',
      io: 'input',
      widget: 'trend',
      signal: 'analog',
      range: POSITION_RANGE,
      color: '#38bdf8',
    },
    {
      address: 'D1',
      label: 'Speed',
      io: 'input',
      widget: 'gauge',
      signal: 'analog',
      range: SPEED_RANGE,
      color: '#fbbf24',
    },
    {
      address: 'D20',
      label: 'Speed Reference',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: REFERENCE_RANGE,
      color: '#34d399',
    },
    {
      address: 'D40',
      label: 'Accel Rate',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: RAMP_RANGE,
      color: '#a78bfa',
    },
    {
      address: 'D41',
      label: 'Decel Rate',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: RAMP_RANGE,
      color: '#a78bfa',
    },
    { address: 'Y0', label: 'Run Forward', io: 'output', widget: 'motor', color: '#34d399' },
    { address: 'Y1', label: 'Run Reverse', io: 'output', widget: 'motor', color: '#f97316' },
    { address: 'Y4', label: 'Forks', io: 'output', widget: 'motor', color: '#e879f9' },
  ],
  registers: [
    { address: 'M0', label: 'Pallet released', note: 'set at the drop, cleared back at the pick' },
    { address: 'D30', label: 'Target position', note: 'raw counts; K400 or K3400' },
    { address: 'D31', label: 'Distance to go', note: 'target minus position, signed' },
    { address: 'D32', label: 'Slow-down distance', note: 'K400 empty, K1000 loaded' },
    { address: 'D33', label: 'Slow-down distance, negated', note: 'for the reverse-side compare' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'compare',
    'mov',
    'math',
    'hwire',
    'coil-out',
    'coil-set',
    'coil-reset',
  ],
  maxRungs: 20,
  processId: 'axis',
  scenarios: [
    {
      name: 'One pallet, picked up and put away',
      steps: [
        {
          label: 'The forks close on the waiting pallet',
          holdMs: 4000,
          until: { bits: { X14: true } },
          expectMachine: { jam: false },
        },
        {
          label: 'It carries the pallet out to the drop station',
          holdMs: 40000,
          until: { bits: { X13: true } },
          expectMachine: { jam: false, loaded: true },
        },
        {
          label: 'And sets it down there',
          holdMs: 12000,
          until: { machine: { placed: 1 } },
          expectAnalog: { D0: { min: 3340, max: 3460 } },
          expectMachine: { jam: false, loaded: false },
        },
      ],
    },
    {
      name: 'Two pallets back to back',
      steps: [
        {
          label: 'Run two full cycles',
          holdMs: 140000,
          until: { machine: { placed: 2 } },
          expectMachine: { jam: false },
        },
        {
          label: 'The carriage goes back for the next one and waits there loaded',
          holdMs: 40000,
          until: { bits: { X14: true } },
          expectMachine: { jam: false },
        },
      ],
      // Measured against the reference cycle on the published tables. A program
      // that uses the loaded table for everything still works, and still pays.
      parMs: 43000,
    },
  ],
};
