import type { AnalogRange, PuzzleSpec } from '../types.js';
import { POSITION_RANGE, RAMP_RANGE, REFERENCE_RANGE, SPEED_RANGE } from './37-axis-jog.js';

/** Hook travel: 0 is fully raised, 4000 is fully lowered. */
export const HOIST_RANGE: AnalogRange = {
  countMin: 0,
  countMax: 4000,
  min: 0,
  max: 3000,
  units: 'mm down',
  decimals: 0,
};

/** Sway amplitude: how far the load swings either side of vertical. */
export const SWAY_RANGE: AnalogRange = {
  countMin: 0,
  countMax: 1000,
  min: 0,
  max: 500,
  units: 'mm',
  decimals: 0,
};

export const axisCrane: PuzzleSpec = {
  kind: 'ladder',
  slug: 'axis-crane',
  title: 'Stacker Crane: Put-Away',
  difficulty: 'hard',
  order: 40,
  category: 'motion',
  summary: 'Two axes, two ramp tables and a load on a rope that keeps swinging after the trolley stops.',
  briefing: [
    'The same carriage, now working as a stacker crane: the forks hang from a hoist',
    'rope instead of sitting on the frame. Everything you already know still applies,',
    'and one new thing does not.',
    '',
    'A load on a rope is a pendulum. When the trolley changes speed the load swings,',
    'and it keeps swinging for several seconds after the trolley has stopped dead. Put',
    'the hook down into a rack while that is happening and the pallet catches the',
    'upright. The drive cannot see this. The sway meter can.',
    '',
    '## Equipment',
    '- D0 POSITION, D1 SPEED, D20 SPEED REFERENCE, D40 ACCEL, D41 DECEL: as before.',
    '- D2 HOOK POSITION: 0 is fully raised, 4000 fully lowered.',
    '- D21 HOIST SPEED REFERENCE: how fast the rope pays out. Load K4000 and leave it.',
    '- D3 SWAY: how far the load is swinging either side of straight down. It is an',
    '  amplitude, not an angle, so it falls steadily instead of passing through zero',
    '  four times a second the way the load itself does.',
    '- X15 HOOK UP, X16 HOOK DOWN: the hoist end limits.',
    '- X17 SWAY OK: true once the swing has died down enough to lower into a rack.',
    '- X12 AT PICK, X13 AT DROP, X14 LOAD ON FORKS, X0 AUTO.',
    '- Y2 HOIST UP, Y3 HOIST DOWN, Y4 FORKS, Y0 and Y1 as before.',
    '',
    '## Sequence of operation',
    '1. At a station, stopped, with the swing settled, lower the hook to X16.',
    '2. At the bottom, close the forks at the pick station or open them at the drop',
    '   station. That is the transfer.',
    '3. Raise the hook back to X15.',
    '4. Traverse to the other station, on the ramp table that matches the load.',
    '5. Wait for the swing to settle, and start again.',
    '',
    '## Interlocks and safety',
    '- Lowering the hook while the load is swinging catches the rack and wrecks the',
    '  pallet. X17 is the permission for that move.',
    '- The forks only transfer with the hook fully down and the trolley stopped.',
    '  Opening them with the hook up drops the pallet from height.',
    '- The loaded and empty ramp tables are the same as the last work order: K1000 and',
    '  K1200 loaded, K2000 and K2500 empty.',
    '- The trolley must not traverse with the hook down.',
    '- Overshooting the drop station with a pallet on board hits the rack face, exactly',
    '  as it did on the traverse.',
    '',
    '## Field notes',
    '- How much swing a move leaves behind depends on how long the ramp took, not just',
    '  how steep it was. A ramp that runs for about as long as the load takes to swing',
    '  once cancels most of its own excitation. The published tables are a ceiling, not',
    '  a recipe, and there is a gentler pair inside them that arrives later and settles',
    '  sooner. The cycle time knows the difference.',
    '',
    '## Acceptance',
    '- One pallet lifted from the pick station and put away at the drop station, with',
    '  the crane back where it started ready for the next one.',
    '- Nothing tripped, nothing dropped, nothing caught.',
  ].join('\n'),
  hints: [
    'One latch runs the whole thing. Set M1 when the trolley is at a station, stopped, ' +
      'with X17 made and a transfer due there (empty at the pick, loaded at the drop). ' +
      'Reset it when the transfer has happened (loaded at the pick, empty at the drop).',
    'With M1 as "a transfer is pending", the hoist writes itself: M1 and NC X16 lowers, ' +
      'NC M1 and NC X15 raises. The trolley only moves on X15 with NC M1, which keeps ' +
      'it from traversing with the hook down.',
    'The forks want their own latch: set M2 at the bottom at the pick station, reset ' +
      'it at the bottom at the drop station, and drive Y4 straight from M2.',
    'If the crane jams the first time it reaches the rack, it lowered before the swing ' +
      'had gone. X17 belongs in the rung that starts the transfer, not somewhere after ' +
      'the hook is already moving.',
  ],
  devices: [
    { address: 'X0', label: 'Auto', io: 'input', widget: 'toggle' },
    { address: 'X12', label: 'At Pick Station', io: 'input', widget: 'sensor' },
    { address: 'X13', label: 'At Drop Station', io: 'input', widget: 'sensor' },
    { address: 'X14', label: 'Load On Forks', io: 'input', widget: 'sensor' },
    { address: 'X15', label: 'Hook Up', io: 'input', widget: 'sensor' },
    { address: 'X16', label: 'Hook Down', io: 'input', widget: 'sensor' },
    { address: 'X17', label: 'Sway OK', io: 'input', widget: 'sensor' },
    {
      address: 'D0',
      label: 'Position',
      io: 'input',
      widget: 'trend',
      signal: 'analog',
      range: POSITION_RANGE,
      color: '#38bdf8',
    },
    {
      address: 'D1',
      label: 'Speed',
      io: 'input',
      widget: 'gauge',
      signal: 'analog',
      range: SPEED_RANGE,
      color: '#fbbf24',
    },
    {
      address: 'D2',
      label: 'Hook Position',
      io: 'input',
      widget: 'bar',
      signal: 'analog',
      range: HOIST_RANGE,
      color: '#94a3b8',
    },
    {
      address: 'D3',
      label: 'Sway',
      io: 'input',
      widget: 'trend',
      signal: 'analog',
      range: SWAY_RANGE,
      color: '#f472b6',
    },
    {
      address: 'D20',
      label: 'Speed Reference',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: REFERENCE_RANGE,
      color: '#34d399',
    },
    {
      address: 'D21',
      label: 'Hoist Reference',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: REFERENCE_RANGE,
      color: '#34d399',
    },
    {
      address: 'D40',
      label: 'Accel Rate',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: RAMP_RANGE,
      color: '#a78bfa',
    },
    {
      address: 'D41',
      label: 'Decel Rate',
      io: 'output',
      widget: 'bar',
      signal: 'analog',
      range: RAMP_RANGE,
      color: '#a78bfa',
    },
    { address: 'Y0', label: 'Run Forward', io: 'output', widget: 'motor', color: '#34d399' },
    { address: 'Y1', label: 'Run Reverse', io: 'output', widget: 'motor', color: '#f97316' },
    { address: 'Y2', label: 'Hoist Up', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y3', label: 'Hoist Down', io: 'output', widget: 'motor', color: '#38bdf8' },
    { address: 'Y4', label: 'Forks', io: 'output', widget: 'motor', color: '#e879f9' },
  ],
  registers: [
    { address: 'M1', label: 'Transfer pending', note: 'the hook should be down' },
    { address: 'M2', label: 'Forks closed', note: 'drives Y4 directly' },
    { address: 'D30', label: 'Target position', note: 'raw counts; K400 or K3400' },
    { address: 'D31', label: 'Distance to go', note: 'target minus position, signed' },
    { address: 'D32', label: 'Slow-down distance', note: 'K400 empty, K1000 loaded' },
    { address: 'D33', label: 'Slow-down distance, negated', note: 'for the reverse-side compare' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'compare',
    'mov',
    'math',
    'hwire',
    'coil-out',
    'coil-set',
    'coil-reset',
  ],
  maxRungs: 26,
  processId: 'axis',
  scenarios: [
    {
      name: 'One pallet put away',
      steps: [
        {
          label: 'Switch to auto; the hook comes down and the forks take the pallet',
          setInputs: { X0: true },
          holdMs: 20000,
          until: { bits: { X14: true } },
          expectMachine: { jam: false },
        },
        {
          label: 'The hook lifts clear before the trolley moves',
          holdMs: 20000,
          until: { bits: { X15: true } },
          expect: { X14: true },
          expectMachine: { jam: false },
        },
        {
          label: 'It traverses to the rack and waits out the swing',
          holdMs: 60000,
          until: { bits: { X13: true, X17: true } },
          expectAnalog: { D0: { min: 3340, max: 3460 } },
          expectMachine: { jam: false },
        },
        {
          label: 'Only then does it lower and set the pallet down',
          holdMs: 30000,
          until: { machine: { placed: 1 } },
          expectMachine: { jam: false, loaded: false },
        },
        {
          label: 'And it returns to the pick station for the next one',
          holdMs: 60000,
          until: { bits: { X12: true, X15: true } },
          expectMachine: { jam: false },
        },
      ],
      // Measured against the reference cycle on the published tables. The
      // gentler pair the briefing hints at settles sooner and beats this.
      parMs: 41000,
    },
  ],
};
