import type { PuzzleSpec } from '../types.js';
import { CODE_RANGE, CRANE_DEVICES, TARGET_REGISTERS, WMS_REGISTERS } from './41-asrs-drive.js';

export const asrsPutAway: PuzzleSpec = {
  kind: 'ladder',
  slug: 'asrs-put-away',
  title: 'Aisle Crane: First Put-Away',
  difficulty: 'easy',
  order: 42,
  category: 'warehouse',
  summary: 'Take the fitter off the panel: one relay per stop, and the crane puts a pallet away on its own.',
  briefing: [
    'The same crane, and now nobody is stood at the test panel. One pallet is waiting on',
    'the goods-in conveyor and it needs to be in the rack, and the program has to decide',
    'when to go, when to reach and when to move on.',
    '',
    'The machine you commissioned does not change. Keep the move block, keep the arrival',
    'relay, and add the thing that was missing: something that says which station is the',
    'target right now, and knows when that stop is finished.',
    '',
    '## Equipment',
    '- Everything from commissioning: X20 to X25 along the rail, X26 and X27 on the mast,',
    '  X28 and X29 at the ends of the fork stroke, D0 POSITION and D1 LEVEL, and the five',
    '  coils Y0 to Y4.',
    '- X13 SLOT OCCUPIED: the photo-eye on the carriage, looking into whichever slot the',
    '  crane is parked at. New on this job.',
    '- D13 CODE ON FORKS and D12 GOODS IN CODE: what material you are holding, and what',
    '  is waiting on the conveyor. Nothing on this job depends on them yet.',
    '- X12 GOODS IN READY and X3 LOAD ON FORKS.',
    '- D101 to D104 and D201 to D204: the WMS slot table, one register per slot, holding',
    '  the material code stored there or 0 for an empty slot. Nothing on this job has to',
    '  search it. It is simply where "bay 2 level 2 is empty" comes from, and the next',
    '  work order is about reading it properly.',
    '- X0 AUTO: the cycle-start switch, and the only thing an operator touches now.',
    '',
    '## Sequence of operation',
    '1. In auto, drive to the goods-in conveyor at position 0, level 2.',
    '2. Run the fork all the way out and all the way back in again. That is the whole',
    '   transfer: the pallet comes with you when the stroke completes.',
    '3. Drive to bay 2, level 2, which the WMS shows as empty.',
    '4. Run the fork out and back again to leave the pallet there.',
    '5. Return to position 0, level 1, and stop. Do not start again.',
    '',
    '## Interlocks and safety',
    '- The two rules from commissioning still hold and are still yours to enforce:',
    '  nothing travels or lifts unless X28 says the fork is home, and the fork never',
    '  leaves home unless the crane is standing on both of its target sensors.',
    '- The end stops are mechanical. Driving into one simply holds the crane.',
    '',
    '## Field notes',
    '- Three stops means three relays, latched one at a time: M1 go and collect, M2 go',
    '  and store, M3 go home. One rung then loads D52 and D53 from whichever relay is up,',
    '  and the move block you already have does the rest without being told which stop it',
    '  is serving.',
    '- Several rungs writing D52 is still the value-selection idiom rather than a double',
    '  coil, because a MOV only writes while its own row conducts.',
    '- The fork has to run out once per stop and not once per scan, so it needs a memory:',
    '  latch M11 when X29 makes, drive the fork from "at target and M11 not yet set", and',
    '  clear M11 whenever the crane is not at its target. That one relay turns a held',
    '  button into an automatic stroke.',
    '- Advancing the step chain in reverse rung order is worth the thought: a step that',
    '  has just been set must not also be completed further down the same scan, because',
    '  the target registers it depends on have not been reloaded yet.',
    '',
    '## Acceptance',
    '- The pallet from goods-in is in bay 2, level 2.',
    '- The crane is back at position 0, level 1, with its fork home.',
    '- Nothing folded and nothing was dropped.',
  ].join('\n'),
  hints: [
    'Start from the commissioning program. The move block and the M0 arrival rung carry ' +
      'over unchanged; what replaces the panel is one rung that loads D52 and D53 from ' +
      'the live step relay, and a chain that moves the step on.',
    'The job is three steps, so latch three relays one at a time - M1 go and collect, ' +
      'M2 go and store, M3 go home - and let one rung load D52 and D53 from whichever ' +
      'step is active. Give the idle case a row of its own so the crane has a target ' +
      'before the cycle starts.',
    'For the fork, latch M11 when X29 makes and drive Y4 from "at target and not M11". ' +
      'The fork then goes out once, comes back on its own, and M11 tells the step chain ' +
      'the transfer is finished. Clear M11 whenever the crane is not at its target.',
    'Advance each step on "this step is live, the transfer is done, and the fork is ' +
      'home again", and write those rungs from the last step upwards. Set M4 at the end ' +
      'and put an NC contact on it in the start rung, or the cycle runs forever.',
  ],
  devices: [
    { address: 'X0', label: 'Auto', io: 'input', widget: 'toggle' },
    { address: 'X12', label: 'Goods In Ready', io: 'input', widget: 'sensor' },
    ...CRANE_DEVICES,
    {
      address: 'D12',
      label: 'Goods In Code',
      io: 'input',
      widget: 'bar',
      signal: 'analog',
      range: CODE_RANGE,
      color: '#fbbf24',
    },
  ],
  registers: [
    { address: 'M1', label: 'Step 1: collect', note: 'at goods-in, position 0 level 2' },
    { address: 'M2', label: 'Step 2: store', note: 'at bay 2 level 2' },
    { address: 'M3', label: 'Step 3: go home', note: 'position 0 level 1' },
    { address: 'M4', label: 'Cycle finished', note: 'stops the job restarting' },
    { address: 'M0', label: 'At target', note: 'D0 matches D52 and D1 matches D53' },
    { address: 'M11', label: 'Transfer done', note: 'the fork has been all the way out' },
    ...TARGET_REGISTERS,
    ...WMS_REGISTERS,
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'compare',
    'mov',
    'hwire',
    'coil-out',
    'coil-set',
    'coil-reset',
  ],
  maxRungs: 20,
  processId: 'warehouse',
  scenarios: [
    {
      name: 'One pallet into the rack',
      steps: [
        {
          label: 'Switch to auto; the crane collects the pallet from goods-in',
          setInputs: { X0: true },
          holdMs: 30000,
          until: { bits: { X3: true } },
          expectMachine: { jam: false },
        },
        {
          label: 'It carries it to bay 2 and leaves it in the reserve level',
          holdMs: 30000,
          until: { machine: { storedAway: 1 } },
          expectMachine: { jam: false, slot22: 1 },
        },
        {
          label: 'And returns to the aisle head with the fork home',
          holdMs: 30000,
          until: { bits: { X20: true, X26: true, X28: true } },
          expectMachine: { jam: false, storedAway: 1, carrying: false },
        },
      ],
      parMs: 6600,
    },
  ],
};
