import type { PuzzleSpec } from '../types.js';
import { CODE_RANGE, CRANE_DEVICES, TARGET_REGISTERS, WMS_REGISTERS } from './41-asrs-drive.js';

export const asrsReplenish: PuzzleSpec = {
  kind: 'ladder',
  slug: 'asrs-replenish',
  title: 'Goods In',
  difficulty: 'hard',
  order: 45,
  category: 'warehouse',
  summary: 'Stock arrives while orders are going out, and the inbound conveyor will not wait.',
  briefing: [
    'Goods in is running again. Pallets arrive on the conveyor above line A, at position',
    '0 level 2, and they have to go into the rack. Line A is still calling for material',
    'at the same time, off the conveyor directly below.',
    '',
    'So the crane now has two different jobs, and they run in opposite directions. A',
    'retrieval collects from a slot and delivers to a station. A put-away collects from',
    'goods in and delivers to a slot. Same crane, same fork, same move block - the only',
    'thing that changes is where it picks up and where it puts down.',
    '',
    'The inbound conveyor holds two pallets. When a third arrives and there is no room,',
    'goods in stops, and a stopped goods in is a failed run exactly like a stopped line.',
    'Feeding the line is more urgent than putting stock away, but "more urgent" is not',
    '"instead of".',
    '',
    '## Equipment',
    '- X12 GOODS IN READY: a pallet is waiting on the inbound conveyor.',
    '- D12 GOODS IN CODE: what material it is.',
    '- The rack starts with two slots empty. As orders go out, more open up.',
    '- Y5 NO STOCK and Y6 PUT AWAY: light Y6 while the crane is working an inbound',
    '  pallet, so the shift leader can see which job is in hand.',
    '',
    '## Sequence of operation',
    '1. If line A is calling and the rack has what it wants, run a retrieval.',
    '2. Otherwise, if a pallet is waiting at goods in and the rack has a free slot, run',
    '   a put-away: collect from position 0 level 2, and deliver to the nearest empty',
    '   slot.',
    '3. If there is nothing to do, stand still.',
    '',
    '## Interlocks and safety',
    '- A slot holds one pallet. Pushing a second one in wrecks both.',
    '- Nothing goes back out onto the inbound conveyor. It only runs one way.',
    '- The line still only accepts what it asked for, and still only two at a time.',
    '',
    '## Field notes',
    '- An empty slot is a slot whose register reads zero, so the search you already have',
    '  will find one without changing a rung: run the same eight tests a second time',
    '  against K=0, into their own registers, and the nearest free slot falls out.',
    '- Whichever job is in hand, the crane collects somewhere and delivers somewhere. It',
    '  is worth writing the target rung as those two ideas rather than as four cases.',
    '- Put-aways are not free time. Every pallet you store now is a pallet that is there',
    '  to be picked later, and every one you leave on the conveyor is one closer to',
    '  stopping goods in.',
    '',
    '## Acceptance',
    '- Line A never stops.',
    '- Goods in never backs up.',
    '- Four pallets put away and four delivered, with nothing driven into an occupied',
    '  slot.',
  ].join('\n'),
  hints: [
    'Add one relay for "this cycle is a put-away", decided at the same moment as the ' +
      'rest of the cycle: set it when the line is not calling (or has nothing in stock) ' +
      'and goods in is ready, clear it otherwise. Drive Y6 straight from it.',
    'Run the search twice, with its own destination registers and its own found relay ' +
      'each time: once against D10 to locate the order, and once against K=0 to locate a ' +
      'free slot. Nothing inside the eight tests changes; only what they are compared ' +
      'against does.',
    'The target rung is four rows now, not two: collecting on a retrieval means the ' +
      'chosen slot and collecting on a put-away means position 0 level 2, while ' +
      'delivering on a retrieval means the station and delivering on a put-away means ' +
      'the chosen slot.',
    'If goods in backs up, the crane was probably waiting for a call it could have ' +
      'served later. There is slack in a line\'s conveyor - two pallets - and none at ' +
      'all in a decision to stand still with a pallet waiting upstairs.',
  ],
  devices: [
    { address: 'X4', label: 'Line A Running', io: 'input', widget: 'toggle' },
    { address: 'X10', label: 'Call A', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Goods In Ready', io: 'input', widget: 'sensor' },
    ...CRANE_DEVICES,
    {
      address: 'D10',
      label: 'Line A Demand',
      io: 'input',
      widget: 'bar',
      signal: 'analog',
      range: CODE_RANGE,
      color: '#fbbf24',
    },
    {
      address: 'D12',
      label: 'Goods In Code',
      io: 'input',
      widget: 'bar',
      signal: 'analog',
      range: CODE_RANGE,
      color: '#4ade80',
    },
    { address: 'Y5', label: 'No Stock', io: 'output', widget: 'lamp', color: '#f87171' },
    { address: 'Y6', label: 'Put Away', io: 'output', widget: 'lamp', color: '#4ade80' },
  ],
  registers: [
    { address: 'M0', label: 'At target', note: 'D0 matches D52 and D1 matches D53' },
    { address: 'M1', label: 'Cycle running', note: 'one job, start to finish' },
    { address: 'M2', label: 'Order slot found', note: 'the rack has what the line wants' },
    { address: 'M3', label: 'Carrying', note: 'latched off X3; picks the target' },
    { address: 'M4', label: 'Empty slot found', note: 'there is room for an inbound pallet' },
    { address: 'M6', label: 'Put-away cycle', note: 'held for the whole cycle; drives Y6' },
    { address: 'M11', label: 'Transfer done', note: 'the fork has been all the way out' },
    { address: 'D50', label: 'Order slot bay', note: 'where the order is picked from' },
    { address: 'D51', label: 'Order slot level', note: 'where the order is picked from' },
    { address: 'D56', label: 'Empty slot bay', note: 'where the inbound pallet goes' },
    { address: 'D57', label: 'Empty slot level', note: 'where the inbound pallet goes' },
    ...TARGET_REGISTERS,
    { address: 'D61', label: 'Distance to bay 1', note: 'from the aisle head' },
    { address: 'D62', label: 'Distance to bay 2', note: 'from the aisle head' },
    { address: 'D63', label: 'Distance to bay 3', note: 'from the aisle head' },
    { address: 'D64', label: 'Distance to bay 4', note: 'from the aisle head' },
    { address: 'D65', label: 'Best order distance', note: 'start it at K=99' },
    { address: 'D66', label: 'Best empty distance', note: 'start it at K=99' },
    ...WMS_REGISTERS,
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'compare',
    'mov',
    'math',
    'hwire',
    'coil-out',
    'coil-set',
    'coil-reset',
  ],
  maxRungs: 45,
  processId: 'warehouse',
  scenarios: [
    {
      name: 'Orders out and stock in',
      steps: [
        {
          label: 'The line calls and a pallet is already waiting upstairs',
          setInputs: { X4: true },
          holdMs: 60000,
          until: { machine: { storedAway: 1 } },
          expectMachine: { jam: false, starved: false, blocked: false },
        },
        {
          // The two latches are the real assertion here: neglect the line and
          // `starved` catches it, neglect goods in and `blocked` does.
          label: 'Both jobs keep running without either backing up',
          holdMs: 220000,
          until: { machine: { deliveredA: 4 } },
          expectMachine: { jam: false, starved: false, blocked: false },
        },
      ],
    },
  ],
};
