import type { PuzzleSpec } from '../types.js';
import { CODE_RANGE, CRANE_DEVICES, TARGET_REGISTERS, WMS_REGISTERS } from './41-asrs-drive.js';

export const asrsDualCycle: PuzzleSpec = {
  kind: 'ladder',
  slug: 'asrs-dual-cycle',
  title: 'Dual Command',
  difficulty: 'hard',
  order: 46,
  category: 'warehouse',
  summary: 'Both lines, goods in and one crane at full rate. Stop running the aisle empty.',
  briefing: [
    'Full production. Line A and line B both calling, goods in arriving, one crane.',
    '',
    'Add the three jobs up against the time a cycle takes and there is very little left',
    'over. Every pallet the lines eat has to be replaced, so the crane now does two',
    'transfers for every one it did on the first job of this category, and it does them',
    'at opposite ends of the aisle.',
    '',
    'Look at what the crane does on a put-away. It carries a pallet from goods in to a',
    'slot, and then it drives back down the aisle with nothing on the fork. A retrieval',
    'does the same thing in reverse. Half of every trip is empty, and the empty half is',
    'free to carry something if you plan it that way: put a pallet away and collect the',
    'next order from a slot before coming back. One trip, two pallets. That is a dual',
    'command cycle, and it is what buys back the margin this shift does not have.',
    '',
    '## Equipment',
    '- Everything from the previous jobs: both lines, both demand registers, goods in,',
    '  the WMS table, the crane.',
    '- X6 STOP: the shift-end switch. Finish what is on the fork, park at position 0',
    '  level 1, and start nothing new.',
    '- Y7 RUNNING: on whenever the crane has a job in hand.',
    '',
    '## Sequence of operation',
    '1. Decide the next job from what is waiting: a line calling, or a pallet at goods',
    '   in, or both.',
    '2. Where both are waiting, do them on one trip. Collect the inbound pallet, store',
    '   it in the nearest empty slot, then collect the order from its slot on the way',
    '   back to the station that asked for it.',
    '3. Where only one is waiting, run it on its own.',
    '4. On STOP, finish the job in hand and park.',
    '',
    '## Interlocks and safety',
    '- One pallet on the fork at a time. A dual cycle is two transfers in one trip, not',
    '  two pallets in one hand.',
    '- Neither line accepts a material it did not ask for, and neither conveyor holds',
    '  more than two.',
    '- A slot holds one pallet, and nothing goes back out to goods in.',
    '- Any line stopping, and goods in backing up, both fail the run.',
    '',
    '## Field notes',
    '- The put-away half and the retrieval half each need their own chosen slot, because',
    '  the crane is holding one while it works out the other. Two pairs of registers,',
    '  and the search run twice - once for an empty slot, once for the material.',
    '- The order of the two halves is not arbitrary. Storing first frees a slot search',
    '  from having to avoid the pallet you are still carrying, and it puts the crane',
    '  further down the aisle before it looks for the order.',
    '- Deciding the whole trip up front, before the crane moves, is much easier to get',
    '  right than deciding it a leg at a time.',
    '- Do not bolt a put-away onto a trip that starts at the far end of the aisle. The',
    '  empty run back to goods in costs more than doing the two jobs separately would.',
    '  But never stand still for want of a job either: with no order to fetch, go and do',
    '  the put-away from wherever you are, or the aisle deadlocks waiting for stock that',
    '  only a put-away could deliver.',
    '',
    '## Acceptance',
    '- Six deliveries to line A and six to line B, all of them the material asked for.',
    '- Six pallets put away.',
    '- Neither line stops, goods in never backs up, nothing crashes.',
    '- On STOP the crane is parked at the aisle head with nothing on the fork.',
  ].join('\n'),
  hints: [
    'Start from the working program and change only the decision. Everything that drives ' +
      'the crane - the move block, the fork latch, the target rung - stays as it is.',
    'A trip is a list of stops. Give it two chosen slots (say D50 and D51 for the empty ' +
      'slot, D56 and D57 for the order) and a small step counter, and let the target rung ' +
      'read the counter: step 1 goods in, step 2 the empty slot, step 3 the order slot, ' +
      'step 4 the station. A retrieval-only trip starts at step 3, a put-away-only trip ' +
      'finishes at step 2.',
    'Run the search twice in the same scan and it will give you the same answer twice. ' +
      'Run it once for K=0 into the put-away pair and once for the demand into the order ' +
      'pair, each with its own found relay and its own best-distance register.',
    'If goods in blocks near the end, the crane was doing single trips when it had both ' +
      'jobs waiting. If a line starves early, check that a trip which cannot find an ' +
      'empty slot still does the retrieval instead of standing still.',
  ],
  devices: [
    { address: 'X4', label: 'Line A Running', io: 'input', widget: 'toggle' },
    { address: 'X5', label: 'Line B Running', io: 'input', widget: 'toggle' },
    { address: 'X6', label: 'Stop', io: 'input', widget: 'toggle' },
    { address: 'X10', label: 'Call A', io: 'input', widget: 'sensor' },
    { address: 'X11', label: 'Call B', io: 'input', widget: 'sensor' },
    { address: 'X12', label: 'Goods In Ready', io: 'input', widget: 'sensor' },
    ...CRANE_DEVICES,
    {
      address: 'D10',
      label: 'Line A Demand',
      io: 'input',
      widget: 'bar',
      signal: 'analog',
      range: CODE_RANGE,
      color: '#fbbf24',
    },
    {
      address: 'D11',
      label: 'Line B Demand',
      io: 'input',
      widget: 'bar',
      signal: 'analog',
      range: CODE_RANGE,
      color: '#fb923c',
    },
    {
      address: 'D12',
      label: 'Goods In Code',
      io: 'input',
      widget: 'bar',
      signal: 'analog',
      range: CODE_RANGE,
      color: '#4ade80',
    },
    { address: 'Y5', label: 'No Stock', io: 'output', widget: 'lamp', color: '#f87171' },
    { address: 'Y6', label: 'Put Away', io: 'output', widget: 'lamp', color: '#4ade80' },
    { address: 'Y7', label: 'Running', io: 'output', widget: 'lamp', color: '#38bdf8' },
  ],
  registers: [
    { address: 'M0', label: 'At target', note: 'D0 matches D52 and D1 matches D53' },
    { address: 'M1', label: 'Trip running', note: 'one trip, however many stops it has' },
    { address: 'M2', label: 'Empty slot found', note: 'somewhere to put an inbound pallet' },
    { address: 'M4', label: 'Order slot found', note: 'somewhere to fetch the order from' },
    { address: 'M5', label: 'Serving line B', note: 'held for the whole trip' },
    { address: 'M6', label: 'Put away this trip', note: 'drives Y6' },
    { address: 'M7', label: 'Retrieve this trip', note: 'the trip has an order leg' },
    { address: 'M11', label: 'Transfer done', note: 'the fork has been all the way out' },
    { address: 'D40', label: 'Trip step', note: 'K=1 goods in, K=2 store, K=3 collect, K=4 deliver' },
    { address: 'D50', label: 'Empty slot bay', note: 'where the inbound pallet goes' },
    { address: 'D51', label: 'Empty slot level', note: 'where the inbound pallet goes' },
    { address: 'D56', label: 'Order slot bay', note: 'where the order is picked from' },
    { address: 'D57', label: 'Order slot level', note: 'where the order is picked from' },
    ...TARGET_REGISTERS,
    { address: 'D61', label: 'Distance to bay 1', note: 'from the station being served' },
    { address: 'D62', label: 'Distance to bay 2', note: 'from the station being served' },
    { address: 'D63', label: 'Distance to bay 3', note: 'from the station being served' },
    { address: 'D64', label: 'Distance to bay 4', note: 'from the station being served' },
    { address: 'D65', label: 'Best empty distance', note: 'start it at K=99' },
    { address: 'D66', label: 'Best order distance', note: 'start it at K=99' },
    { address: 'D70', label: 'Material wanted', note: 'copied from D10 or D11' },
    ...WMS_REGISTERS,
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'compare',
    'mov',
    'math',
    'hwire',
    'coil-out',
    'coil-set',
    'coil-reset',
  ],
  maxRungs: 50,
  processId: 'warehouse',
  scenarios: [
    {
      name: 'A full shift on one crane',
      steps: [
        {
          label: 'Line A opens with goods in already running',
          setInputs: { X4: true },
          holdMs: 40000,
          until: { machine: { deliveredA: 2 } },
          expectMachine: { jam: false, starved: false, blocked: false },
        },
        {
          // Line B lags whichever way the arbiter leans, so it carries the
          // milestone. Everything else the step is testing is carried by the
          // three latches: a line left waiting sets `starved`, a neglected
          // inbound conveyor sets `blocked`, and a bad move sets `jam`.
          label: 'Line B starts up, and now there is not enough crane for single trips',
          setInputs: { X5: true },
          holdMs: 260000,
          until: { machine: { deliveredB: 6 } },
          expectMachine: { jam: false, starved: false, blocked: false },
        },
        {
          label: 'Shift end: finish the trip in hand and park at the aisle head',
          setInputs: { X6: true },
          holdMs: 60000,
          until: { bits: { X20: true, X26: true, X28: true, X3: false } },
          expectMachine: { jam: false, starved: false, blocked: false, carrying: false },
        },
      ],
    },
  ],
};
