import type { PuzzleSpec } from '../types.js';
import { DC_INBOUND_1, DC_MAILBOX, DC_QA, DC_QA_CODE, DC_ROUTES, DC_WRAPPER } from './dc-plant.js';

/** The wrapper line as the night shift left it: three pallets on, none labeled. */
const NIGHT_SHIFT = { w3: '305pn0', w2: '102pn0', w1: '404pn0', w0: '' };

export const dcLabel: PuzzleSpec = {
  kind: 'ladder',
  slug: 'dc-label',
  title: 'Cold Chain Hub: Label What You Wrap',
  difficulty: 'easy',
  order: 55,
  category: 'distribution',
  summary: 'Nothing scans a pallet after QA: keep a table of what is on the wrapper line, and label each one as it comes out.',
  briefing: [
    'Every pallet that leaves the hub is stretch-wrapped and labeled with the dock it',
    'ships from. The wrapper line takes a pallet in, wraps it, stops it at the labeler, and',
    'lets it out onto the outfeed once it has a label.',
    '',
    'Nothing on the line can read a pallet, and the labeler only prints. The one place a',
    'pallet is identified is QA. So your program writes down each code as the pallet goes',
    'onto the line, in order, and reads the oldest one back when a pallet reaches the',
    'labeler. That list is a table in D registers, and keeping it is the new idea today.',
    '',
    'Everything else builds on commissioning: the same mailbox, the same pending relays',
    'and bookings, with one more order and two more bookings.',
    '',
    '## Equipment',
    '- From commissioning: the mailbox (D0, D1, Y0, X0), IN1 (location 1, X3) and QA',
    '  (location 10, X5, X6). Every pallet passes QA today, so there is no quarantine.',
    '- D5 QA PALLET CODE: what QA read, as product x 100 + lot. 305 is product 3, lot 5.',
    '  Valid while X6 is on.',
    '- The wrapper line: location 50 is its infeed and 51 its outfeed. X10 WRAPPER INFEED',
    '  CLEAR, X11 PALLET AT LABELER, X12 OUTFEED PALLET READY.',
    '- The labeler: put a door number in D2 LABEL DOOR, then pulse Y1 PRINT LABEL. The',
    '  pallet moves on to the outfeed once it is labeled.',
    '- D101 to D104: the door each product ships from, 61 for OUT1 or 62 for OUT2.',
    '  Product 1 is in D101, product 4 in D104.',
    '',
    '## The line table',
    '- D200 is how many pallets are on the line waiting for a label. D201, D202 and on hold',
    '  their codes, the oldest (nearest the labeler) in D201.',
    '- At the start of every run the pallets the night shift left on the line are already',
    '  written in. From then on nothing writes the table but your program.',
    '- Index registers Z0 to Z7 are words like any other. An operand like D201Z0 means',
    '  "register 201 + Z0": with Z0 = 2 it is D203.',
    '',
    '## Your relays',
    '- Pending orders, one at a time: M10 IN1 to QA, M11 QA to the wrapper infeed (50),',
    '  M12 the wrapper outfeed (51) to its door.',
    '- Bookings: M0 QA is taken. M1 a forklift is coming to collect from QA. M2 the',
    '  wrapper infeed is taken. M3 a forklift is coming to collect from the outfeed.',
    '- The labeler: M14 is on for exactly one scan when a label is printed, and M13',
    '  remembers that this pallet has had its label.',
    '- D20 holds the code being labeled and D22 the door just printed, which is where the',
    '  outfeed order delivers to.',
    '',
    '## Sequence of operation',
    '1. Choose an order, only while M10, M11 and M12 are all off. The first that fits wins:',
    '   a. X12 on and M3 off: SET M12 (ship the labeled pallet).',
    '   b. X6 on, M1 off, X10 on and M2 off: SET M11 (QA to the wrapper).',
    '   c. X3 on and M0 off: SET M10 (IN1 to QA).',
    '2. Post it: M10 loads D0 = K1, D1 = K10. M11 loads D0 = K10, D1 = K50. M12 loads',
    '   D0 = K51, D1 = D22. Y0 is on while any of the three is on and X0 is off.',
    '3. On the rising edge of X0, book the order and clear it:',
    '   a. M10 accepted: SET M0, RST M10.',
    '   b. M11 accepted: SET M1, SET M2, RST M0, RST M11, and add D5 to the table.',
    '   c. M12 accepted: SET M3, RST M12.',
    '4. Free the bookings: X5 off resets M1, the falling edge of X10 (the pallet has',
    '   landed on the infeed) resets M2, and X12 off resets M3.',
    '5. Label: when X11 is on, X12 is off, and M3 and M13 are off, turn M14 on and SET',
    '   M13. RST M13 once X11 goes off. On M14, take the oldest code off the table, look',
    '   up its door and print.',
    '',
    '## Adding a code',
    'On the M11 booking row, after the relays, left to right:',
    '',
    '1. MOV D200 Z0: the next free place in the table.',
    '2. MOV D5 D201Z0: write the code there.',
    '3. ADD D200 K1 D200: one more pallet on the line.',
    '',
    '## Taking a code off and printing',
    'On M14, in this order:',
    '',
    '1. MOV D201 D20: keep the oldest code.',
    '2. Move every entry down one: MOV D202 D201, MOV D203 D202, and so on to MOV D206',
    '   D205. Then SUB D200 K1 D200.',
    '3. DIV D20 K100 Z1: the product number. MOV D100Z1 D2: its door. MOV D2 D22: keep',
    '   it for the outfeed order. OUT Y1: print.',
    '',
    '## Interlocks and safety',
    '- A label for the wrong door is a fault, and so is a pallet loaded at a door its label',
    '  does not name. The labeler checks the real pallet, not your table.',
    '- Never send a pallet to a place that is taken or already promised. That is what the',
    '  bookings are for.',
    '',
    '## Field notes',
    '- The table work must run once per pallet, not once per scan. The rising edge of X0',
    '  does that for the add. For the print, a rung with NC M13 into OUT M14 and SET M13',
    '  turns M14 on for one scan only.',
    '- Put the M14 rung above the rungs that use M14, so they all run in the same scan.',
    '- Moves on one row run left to right, so D201 into D20 must come before D202 into',
    '  D201, or the oldest code is lost.',
    '',
    '## Acceptance',
    '- The pallets the night shift left on the line, and every new one after them, are',
    '  labeled for the right door and loaded there.',
    '- Nothing is sent where it cannot go, and the hub never stalls.',
  ].join('\n'),
  hints: [
    'Ten rungs, in the order of the Sequence of operation: three that choose an order, ' +
      'one that loads D0 and D1, one that drives Y0, one that books on X0 (and adds to the ' +
      'table), one that frees bookings, then three for the labeler. The next hints give ' +
      'each rung exactly.',
    'Rungs 1 to 3, choosing. Rung 1: NO X12, NC M3, NC M10, NC M11, NC M12, SET M12. ' +
      'Rung 2: NO X6, NC M1, NC M2, NO X10, NC M10, NC M11, NC M12, SET M11. Rung 3: ' +
      'NO X3, NC M0, NC M10, NC M11, NC M12, SET M10.',
    'Rung 4, three rows. Row 1: NO M10, MOV K1 D0, MOV K10 D1. Row 2: NO M11, MOV K10 D0, ' +
      'MOV K50 D1. Row 3: NO M12, MOV K51 D0, MOV D22 D1. Rung 5: NO M10, NO M11 and ' +
      'NO M12 in parallel, then NC X0, OUT Y0.',
    'Rung 6, three rows. Row 1: rising X0, NO M10, SET M0, RST M10. Row 2: rising X0, ' +
      'NO M11, SET M1, SET M2, RST M0, RST M11, MOV D200 Z0, MOV D5 D201Z0, ADD D200 K1 ' +
      'D200. Row 3: rising X0, NO M12, SET M3, RST M12.',
    'Rung 7, four rows. NC X5, RST M1. Falling X10, RST M2. NC X12, RST M3. NC X11, ' +
      'RST M13.',
    'Rung 8: NO X11, NC X12, NC M3, NC M13, OUT M14, SET M13. Rung 9: NO M14, MOV D201 ' +
      'D20, MOV D202 D201, MOV D203 D202, MOV D204 D203, MOV D205 D204, MOV D206 D205, ' +
      'SUB D200 K1 D200. Rung 10: NO M14, DIV D20 K100 Z1, MOV D100Z1 D2, MOV D2 D22, ' +
      'OUT Y1.',
    'If the first label is wrong, check the order in rung 9: MOV D201 D20 must come ' +
      'before MOV D202 D201. If one label is right and the next is wrong, the table was ' +
      'written twice for one pallet: the add must be on the rising edge of X0.',
  ],
  devices: [...DC_MAILBOX, ...DC_INBOUND_1, ...DC_QA.slice(0, 2), ...DC_QA_CODE, ...DC_WRAPPER, ...DC_ROUTES],
  registers: [
    { address: 'M10', label: 'Order pending: IN1 to QA' },
    { address: 'M11', label: 'Order pending: QA to the wrapper' },
    { address: 'M12', label: 'Order pending: outfeed to its door' },
    { address: 'M0', label: 'QA booked', note: 'a pallet is on QA or on its way there' },
    { address: 'M1', label: 'QA pickup booked' },
    { address: 'M2', label: 'Wrapper infeed booked' },
    { address: 'M3', label: 'Outfeed pickup booked' },
    { address: 'M13', label: 'Labeled', note: 'this pallet at the labeler has had its label' },
    { address: 'M14', label: 'Print pulse', note: 'on for one scan' },
    { address: 'D200', label: 'Line table: pallets', note: 'written by the WMS at the start, then yours' },
    { address: 'D201', label: 'Line table: first code', note: 'D201 onward, nearest the labeler first' },
    { address: 'D20', label: 'Code being labeled' },
    { address: 'D22', label: 'Door on the outfeed pallet' },
    { address: 'Z0', label: 'Index: where to add' },
    { address: 'Z1', label: 'Index: the product' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'contact-rising',
    'contact-falling',
    'compare',
    'mov',
    'math',
    'hwire',
    'coil-out',
    'coil-set',
    'coil-reset',
  ],
  indexRegisters: true,
  maxRungs: 24,
  processId: 'distribution',
  plantConfig: {
    locs: '1,10,50,51,61,62',
    fleet: 1,
    routes: '61,62,62,61',
    ...NIGHT_SHIFT,
    stocktake: 'D200:50',
    in1: '306P,203P,107P',
    inFirst: 3000,
    inEvery: 25_000,
  },
  scenarios: [
    {
      name: 'The night shift\'s pallets',
      steps: [
        {
          label: 'The three pallets left on the line are labeled and loaded',
          holdMs: 190_000,
          until: { machine: { shipped: 3 } },
          expectMachine: { jam: false, stalled: false, blocked: false },
        },
        {
          label: 'The three that come in after them follow through QA and the wrapper',
          holdMs: 250_000,
          until: { machine: { shipped: 6 } },
          expectMachine: { jam: false, stalled: false, blocked: false },
        },
      ],
    },
    {
      name: 'A different line',
      initialMachine: { w3: '401pn0', w2: '', w1: '208pn0', w0: '', in1: '309P,110P' },
      steps: [
        {
          label: 'Two pallets on the line, two more to come, four different doors to get right',
          holdMs: 270_000,
          until: { machine: { shipped: 4 } },
          expectMachine: { jam: false, stalled: false, blocked: false },
        },
      ],
    },
    {
      name: 'An empty line',
      initialMachine: { w3: '', w2: '', w1: '', w0: '', in1: '302P,403P' },
      steps: [
        {
          label: 'Nothing is on the line, so the table starts empty and fills as pallets arrive',
          holdMs: 210_000,
          until: { machine: { shipped: 2 } },
          expectMachine: { jam: false, stalled: false, blocked: false },
        },
      ],
    },
  ],
};
