import type { PuzzleSpec } from '../types.js';
import {
  DC_ASN,
  DC_CALL_OUT1,
  DC_FLOW_LANES,
  DC_INBOUND_1,
  DC_MAILBOX,
  DC_QA,
  DC_QA_CODE,
} from './dc-plant.js';

export const dcFlowLanes: PuzzleSpec = {
  kind: 'ladder',
  slug: 'dc-flow-lanes',
  title: 'Cold Chain Hub: First In, First Out',
  difficulty: 'medium',
  order: 56,
  category: 'distribution',
  summary: 'Three gravity lanes, one table each, and the oldest lot always ships first. Two vehicles now.',
  briefing: [
    'Pallets that pass QA are stored in the flow rack until OUT1 calls for them. Each of its',
    'three lanes is a gentle slope of rollers four pallets deep: a pallet set down at the',
    'back rolls forward, and the one at the front is the only one a vehicle can reach from',
    'the pick face on the other side. What goes in first comes out first, whatever you',
    'would prefer.',
    '',
    'Food ships first expired, first out. A lower lot number is older, and a lot may not',
    'leave while an older lot of the same product is still in the rack. Nothing in the rack',
    'can be read, so to know what is at the front of each lane the program keeps a table of',
    'every lane, and every pallet it ships goes with a shipping notice naming it.',
    '',
    '## Equipment',
    '- The mailbox, IN1 (1) with X3, and QA (10) with X5, X6 and D5 QA PALLET CODE, all as',
    '  before. Every pallet today passes QA.',
    '- Flow lanes F1, F2 and F3, locations 31, 32 and 33. A vehicle loads a lane at its back',
    '  and collects from its front, and the manager knows which face is which.',
    '- D31, D32 and D33: how many pallets are physically in each lane.',
    '- OUT1 (61), and D13 OUT1 CALLING FOR: the product the truck wants next. A call is taken',
    '  the moment an order to OUT1 is accepted, and D13 reads 0 for a few seconds before the',
    '  next one. Answer exactly what it calls for.',
    '- D3 SHIPPING NOTICE CODE: the code of the pallet you are shipping. The manager reads',
    '  it when it accepts an order to OUT1, and the dock checks the pallet against it.',
    '- Two vehicles.',
    '',
    '## The lane tables',
    '- F1\'s table is at D300, F2\'s at D310 and F3\'s at D320, each in the same layout as',
    '  the wrapper table: the count first, then the codes, front of the lane first.',
    '- The WMS has written in what was already in the rack when the run starts.',
    '- SFWRP adds a code to the back of a table and SFRDP takes the front one off, shifting',
    '  the rest down: exactly the moves you wrote by hand for the wrapper line, in one',
    '  block each. The head is the table\'s first register and the length K5 counts it, so a',
    '  K5 table holds four codes.',
    '- The head can be indexed. With Z0 at 10, D300Z0 is F2\'s table.',
    '',
    '## Sequence of operation',
    '1. When OUT1 is calling, find the lane whose front pallet is the called product with',
    '   the lowest code, take that code off its table into D3, and order the lane to OUT1.',
    '2. When QA is done, store the pallet: choose a lane that is empty, or whose last',
    '   pallet is the same product, add its code to that lane\'s table, and order QA to the',
    '   lane.',
    '3. Otherwise bring the next pallet in from IN1 to QA.',
    '',
    '## Interlocks and safety',
    '- Shipping a lot while an older lot of the same product is anywhere in the rack is a',
    '  fault. So is a shipping notice that does not match the pallet, and a pallet OUT1 did',
    '  not call for.',
    '- A vehicle sent to collect from an empty lane is a fault, and a lane holds four.',
    '',
    '## Field notes',
    '- Your tables run ahead of the rack. The moment you order a pallet into a lane it is',
    '  in the table, but it is on a vehicle for another 15 s. Book the lane for as long as a',
    '  move is in flight, so nothing is taken from a lane on the strength of a pallet that',
    '  has not arrived, and release it when the lane\'s count changes.',
    '- Search every lane, busy or not. If the lowest code is in a lane with a move already',
    '  on its way, wait for it: shipping the next lowest from another lane is exactly what',
    '  first expired, first out forbids.',
    '- Keep each lane to one product. A lane whose front is potatoes cannot give you',
    '  tomatoes, however many are behind them.',
    '- The front code of F1 is D301. Its product is that divided by 100. The last code in',
    '  F1\'s table is D300 plus its count, which is an index: move D300 into Z1 and read',
    '  D300Z1.',
    '- Take the code off the table into D3 on the scan you choose the order, before you ask:',
    '  the manager reads D3 when it accepts, not when it delivers.',
    '',
    '## Acceptance',
    '- Every call is filled with the right product, oldest lot first, under a shipping notice',
    '  that names it.',
    '- Everything that arrives is checked and stored, and the loop never stalls.',
  ].join('\n'),
  hints: [
    'Keep the shape: pending relays for three orders (IN1 to QA, QA to a lane, a lane to ' +
      'OUT1), MOVs into D0 and D1 from D26 and D27 where the lane is not a constant, one ' +
      'request, and all pending relays cleared on the rising edge of X0.',
    'Finding the lane is a small search. Every scan: MOV K0 into D29 and K9999 into D28. Then ' +
      'one rung per lane: count above 0, front product equal to D13, front code below D28, ' +
      'into MOV of the front code into D28 and the lane number into D29. Then ship only if ' +
      'the lane in D29 is not booked.',
    'Shipping, on the scan you choose it: D29 into D27, D29 minus K31 into Z0, Z0 times K10 ' +
      'into Z0, then SFRDP D300Z0 into D3 with K5. Storing, on the rising edge of its pending ' +
      'relay: the same arithmetic from D26 into another Z, then SFWRP D5 into D300 indexed.',
    'Book a lane by setting a relay and copying its count, D31 for F1, into a register of ' +
      'your own. Release it when the count no longer equals the copy. If a vehicle finds a ' +
      'lane empty, a lane was shipped from while a pallet was still on its way into it.',
  ],
  devices: [
    ...DC_MAILBOX,
    ...DC_INBOUND_1,
    ...DC_QA.slice(0, 2),
    ...DC_QA_CODE,
    ...DC_FLOW_LANES,
    ...DC_CALL_OUT1,
    ...DC_ASN,
  ],
  registers: [
    { address: 'D300', label: 'F1 table', note: 'count, then D301 to D304 front first' },
    { address: 'D310', label: 'F2 table', note: 'count, then D311 to D314 front first' },
    { address: 'D320', label: 'F3 table', note: 'count, then D321 to D324 front first' },
  ],
  allowedInstructions: [
    'contact-no',
    'contact-nc',
    'contact-rising',
    'contact-falling',
    'compare',
    'mov',
    'math',
    'sfwr',
    'sfrd',
    'hwire',
    'coil-out',
    'coil-set',
    'coil-reset',
  ],
  indexRegisters: true,
  maxRungs: 36,
  processId: 'distribution',
  plantConfig: {
    locs: '1,10,31,32,33,61',
    fleet: 2,
    asn: true,
    c31: '303pn0,304pn0',
    c32: '401pn0',
    stocktake: 'D300:31,D310:32,D320:33',
    in1: '305P,402P,306P,403P',
    inFirst: 2000,
    inEvery: 12_000,
    calls61: '3,4,3,4,3,4',
  },
  scenarios: [
    {
      name: 'A shift of calls',
      steps: [
        {
          label: 'OUT1 is filled from stock while the first arrivals are checked and stored',
          holdMs: 90_000,
          until: { machine: { shipped: 3 } },
          expectMachine: { jam: false, stalled: false, blocked: false },
        },
        {
          label: 'Every call filled, oldest lot first, each with its shipping notice',
          holdMs: 200_000,
          until: { machine: { shipped: 6 } },
          expectMachine: { jam: false, stalled: false, blocked: false },
        },
      ],
    },
    {
      name: 'Tomatoes in two lanes',
      initialMachine: {
        c31: '305pn0',
        c32: '401pn0,402pn0',
        c33: '303pn0,304pn0',
        in1: '306P,403P',
        calls61: '3,3,4,3,4',
      },
      steps: [
        {
          label: 'The oldest tomatoes are at the back of the rack, not in the first lane',
          holdMs: 200_000,
          until: { machine: { shipped: 5 } },
          expectMachine: { jam: false, stalled: false, blocked: false },
        },
      ],
    },
  ],
};
